### ISSUE TITLE
Add commands to start TIS in the Scaling Criteo: Triton Inference with HugeCTR nb.

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1058]
**Describe the bug**

The commands to start TIS in the `Scaling Criteo: Triton Inference with HugeCTR` nb are missing. We should add it inside the notebook as in [here](https://github.com/NVIDIA/NVTabular/blob/main/examples/getting-started-movielens/inference-HugeCTR/Triton-Inference-with-HugeCTR.ipynb).

**Steps/Code to reproduce bug**

Visit this notebook to identify the issue: https://github.com/NVIDIA/NVTabular/blob/main/examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb

**Comment by bschifferer** [comment]
@rnyak I think we can close the ticket
