### ISSUE TITLE
[QST] Is there a way to do custom aggregations?

### ISSUE THREAD

**Issue by krlng** [NVIDIA-Merlin/NVTabular#1164]
For example I want to get the total progress within a group. My code looks like:

```
cols = ["user", "timecode", "published_at"]

aggs = {
        'timecode': ["first", "last"],
}

usages = cols >> nvt.ops.Groupby(
    groupby_cols="user"
    sort_cols=["published_at"],
    aggs=aggs,
    name_sep="_")

dataset = nvt.Dataset(data)
workflow = nvt.Workflow(all_feats)
sessions_gdf = workflow.fit_transform(dataset).to_ddf()
sessions_gdf["progress"] = sessions_gdf.progress_last - sessions_gdf.progress_first
```

Is there a way to include the subtraction into the workflow? I tested a couple of things like:

```
aggs = {
        'progress': [nvt.ops.LambdaOp(lambda col: col.last() - col.first())],
}

```
or 

```
aggs = {
        'progress': [lambda col: col.last() - col.first()]
}

```
but neither seems to be supported. Is there another way to express this?

**Comment by rnyak** [comment]
@krlng thanks for your question. We do not support custom `aggs` inside the Groupby op. All the supported aggs are given here. 

But how about a workaround like that:


```
cols = ["user", "item", "timecode", "published_at"]

aggs = {
        'timecode': ["first", "last"],
}

usages = cols >> nvt.ops.Groupby(
    groupby_cols=["user","item"],
    sort_cols=["published_at"],
    aggs=aggs,
    name_sep="_")


def timediff(col, gdf):
    col = col - gdf['timecode_first']
    return col
                    

timecode_feat = usages['timecode_last'] >> nvt.ops.LambdaOp(timediff, dependency=usages['timecode_first']) >> nvt.ops.Rename(postfix="_timecode")
filtered_feats = usages + timecode_feat['timecode_last_timecode']
dataset = nvt.Dataset(data)
workflow = nvt.Workflow(filtered_feats)
sessions_gdf = workflow.fit_transform(dataset).to_ddf().compute()
sessions_gdf
```

if you only want to get ` timecode_feat['timecode_last_timecode']` as output feature in your output dataframe, then just do ```
timecode_feat = usages['timecode_last'] >> nvt.ops.LambdaOp(timediff, dependency=usages['timecode_first']) >> nvt.ops.Rename(postfix="_timecode")

dataset = nvt.Dataset(data)
workflow = nvt.Workflow(timecode_feat['timecode_last_timecode'])
sessions_gdf = workflow.fit_transform(dataset).to_ddf().compute()
sessions_gdf
```
Hope that helps.

**Comment by rnyak** [comment]
@krlng is the workaround  above works for you? can we close this issue? thanks.
