### ISSUE TITLE
[Task] Review all notebooks and update with latest API 

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/NVTabular#1177]
**What needs doing**
Customer feedback is that notebooks are not up to date. Many notebooks are developed for older NVTabular version and updates in the API are developed that they are backwards compatible. We should review all notebooks and check if the current explanation and workflows are still the recommended way in terms of new API.

Tasks:
- Update notebooks for latest API
- Standardize notebooks:
-- Standardize notebooks to always use NVTabular if possible.
-- If not, then use cuDF and explain why we use cuDF.
-- If cuDF does not work, use pandas and explain why we use pandas

**Comment by rnyak** [comment]
@bschifferer this also addressed that: https://github.com/NVIDIA-Merlin/NVTabular/issues/1058

**Comment by sohn21c** [comment]
@bschifferer We have updated the notebooks earlier this year. Do you think there's something left in this ticket that needs follow up? or can we close this? 
@viswa-nvidia as fyi,

**Comment by bschifferer** [comment]
I think we need to update the NVTabular notebooks, but we have already tickets for it
