### ISSUE TITLE
[BUG] NVTabular: Support for GCS paths: read + write (Dataset, Workflow classes)

### ISSUE THREAD

**Issue by mengdong** [NVIDIA-Merlin/NVTabular#1230]
**Describe the bug**
Dataset: Only supports reading from GCS, not writing.
Workflow: Does not support GCS paths for reading and writing.

**Steps/Code to reproduce bug**
follow
https://github.com/jarokaz/merlin-on-vertex/blob/main/01-dataset-preprocessing.ipynb

Details will be added by Vertex team.

**Expected behavior**
as description

GCP - n1-highmem-32+4xT4 - nvcr.io/nvidia/merlin/merlin-training:21.09
Driver: NVIDIA-SMI 460.73.01 Driver Version: 460.73.01 CUDA Version: 11.2

**Comment by albert17** [comment]
In the past (Maybe 6 months ago), I have been able to run an NVTabular workflow reading/writing data from/in cloud(gcs and S3) using this script: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/bench/examples/dask-nvtabular-criteo-benchmark.py 

I actually got some perf numbers and was working in how to better configure GCP/AWS VMs storage to get better I/O access.

Not sure if this is exactly the same, but just adding the information.

**Comment by rjzamora** [comment]
>I have been able to run an NVTabular workflow reading/writing data from/in cloud(gcs and S3) using this script: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/bench/examples/dask-nvtabular-criteo-benchmark.py

@albert17 - Are you saying you were able to run your script with `--out-path` pointing to a location in both s3 and gcs? I have not spent much time trying to write to remote storage, but I do recall having problems writing to gcs. I believe I was able to write directly to s3, but needed to copy (`put`) local files to get them into gcs.

**Comment by albert17** [comment]
@rjzamora Yes, I meant that. I added a PR at that time to add the support to the script and to update several components from NVTabular. #540

**Comment by benfred** [comment]
@mengdong for writing the dataset, are you using the latest code? There was a fix pushed about a week ago that at least fixed this for writing the dataset to S3: https://github.com/NVIDIA-Merlin/NVTabular/issues/1214

**Comment by benfred** [comment]
I have a fix for saving the workflow object here https://github.com/NVIDIA-Merlin/NVTabular/pull/1232

**Comment by mengdong** [comment]
Thanks guys,

**Comment by rjzamora** [comment]
Should this be closed? Is `Dataset.to_parquet` working with GCS?

**Comment by benfred** [comment]
@rjzamora I added some code here that uses fsspec to write out datasets https://github.com/NVIDIA-Merlin/NVTabular/issues/1214 and have verified with S3 that this works. I haven't tested with GCS , and we don't have any unittests for GCS (unlike S3).

This *should* work though, since we're using fsspec . The one caveat I guess is that we're not passing along storage_options in the to_parquet call, meaning that auth will have to be done via global environment variables

**Comment by rjzamora** [comment]
>The one caveat I guess is that we're not passing along storage_options in the to_parquet call, meaning that auth will have to be done via global environment variables

Ah - I totally missed this! We should probably add a `storage_options` kwarg to `to_parquet` in case this limitation is too restrictive for some use cases.

**Comment by benfred** [comment]
@bschifferer tested this out and it works
