### ISSUE TITLE
[BUG] Dataset.to_parquet() slow with remote source (Google Cloud Storage)

### ISSUE THREAD

**Issue by leiterenato** [NVIDIA-Merlin/NVTabular#1234]
I am trying to convert CSV files to Parquet using the NVTabular's Dataset.to_parquet() method.
The data is located on a Google Cloud Storage bucket (gs://workshop-datasets/criteo/). This the full Criteo Dataset (24 files ~12GB each).

**Problem**: It takes approximately 4 hours to convert the data to Parquet format.
Compared to the previous version of NVTabular (0.7.0), it is ~6 times slower.
I am using a GCE instance with 96 vCPUs, 360GB of RAM and 4 x T4s.

I experimented 3 different values for the parameter `Dataset.to_parquet(output_files=...)`:
 - default: 4 output files (1 for each GPU/worker)
 - 24 output files (same as the CSV files)
 - 200 output files (approx. 2GB each file)

They have the same performance.

**Steps/Code to reproduce bug**
1) Create the cluster
```python
device_size = device_mem_size()
device_limit = int(device_limit_frac * device_size)
device_pool_size = int(device_pool_frac * device_size)
rmm_pool_size = (device_pool_size // 256) * 256

cluster = LocalCUDACluster(
    n_workers=n_workers,
    device_memory_limit=device_limit,
    rmm_pool_size=rmm_pool_size
)
  ```

2) Create the dataset definition
```python
data_path = 'gs://workshop-datasets/criteo/'
fs_spec = fsspec.filesystem('gs')

valid_paths = []
for i in fs_spec.glob(data_path):
    if fs_spec.isfile(i):
        valid_paths.append(f'gs://{i}')

dataset = nvt.Dataset(
    path_or_source = valid_paths,
    engine='csv',
    names=list(col_dtypes.keys()),
    sep=sep,
    dtypes=col_dtypes,
    part_size=int(part_mem_frac * device_mem_size()),
    client=client,
    assume_missing=True
)
```

3) Execute .to_parquet()
```python
dataset.to_parquet(
    output_path,
    shuffle=shuffle
)
```
`output_path` is a local path.

**Expected behavior**
I expect this process to take no more than 20 minutes.

**Environment details:**
 - Google Cloud
 - 1 x N1 instance with 96 vCPUs and 360GB RAM
 - 4 x T4s
 - Standard Docker image 21.11

**Comment by mengdong** [comment]
I notice when writing to parquet, seems like there is only 1 GPU (out of 4) is active at any time.

**Comment by EvenOldridge** [comment]
@mengdong have we resolved this?  I know we've been working on other related issues.

**Comment by leiterenato** [comment]
Yes, problem solved.
