### ISSUE TITLE
[BUG] nvtabular input datatypes are wrong

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/NVTabular#1238]
**Describe the bug**
Although some columns are float32, NVTabular defines all input datatypes as int32. This causes error when deploying to Triton Inference Server

![image](https://user-images.githubusercontent.com/19567274/141127865-8c2c4f60-7d20-4d74-bff0-a912f6940455.png)

Run criteo example inlcuding the notebook `04-Triton-Inference-with-TF`

**Comment by karlhigley** [comment]
Which fields aren't supposed to be int32 and what error does it cause?

**Comment by bschifferer** [comment]
fields starting with `I` are numerical features and should be float32.

I got errors, when I tried using perf_analyzer with custom data. I think I am not sure, how Triton handles the normal requests, as in the notebook, when we send a float32 to an features with int32

**Comment by EvenOldridge** [comment]
@bschifferer is this still broken?

**Comment by bschifferer** [comment]
I think it is fixed
