### ISSUE TITLE
[BUG] running workflow.fit twice results in ValueError for categorify op. 

### ISSUE THREAD

**Issue by PiotrCzapla** [NVIDIA-Merlin/NVTabular#1244]
**Describe the bug**

The `_category_stats` returns empty dict instead of tuple `disk`, `key` when the cat columns list is empty.
This happens when the fit is executed for the second time on the same categorical columns.

The issue is caused by this return statement in `_group_to_disk` that returns empty dict instead of tuple:
https://github.com/NVIDIA-Merlin/NVTabular/blob/34d01d7e6090d6029ac40010ed79e1558f18759c/nvtabular/ops/categorify.py#L1037

Here is the exception I'm getting:
```
/nvtabular/nvtabular/ops/categorify.py in fit(self, col_selector, ddf)
    340         ]
    341 
--> 342         dsk, key = _category_stats(ddf, self._create_fit_options_from_columns(columns))
    343         return Delayed(key, dsk)
    344 

ValueError: not enough values to unpack (expected 2, got 0)
````

**Steps/Code to reproduce bug**
```
cat_feats = ['user_session'] >> nvt.ops.Categorify()

for _ in [1,2]:                                         # loop to simulate multiple execution of a cell in jupyter notebook
    df_event = nvt.Dataset(raw_df) 
    workflow = nvt.Workflow(cat_feats)
    workflow.fit(df_event)                              # this will fail on the second run
    workflow.transform(df_event).to_ddf().compute()
```

**Expected behavior** 
It shouldn't crash, and the workflow should execute fit again. It is odd that the columns are storing state somewhere, while they look like immutable graph descriptors.
 
**Environment**
The issue seems to be in the current main branch of the NVTabular, since this is syntax error you get it always no matter how the lib was installed.

**Comment by PiotrCzapla** [comment]
For anyone trying to incrementally test their transformation and hitting this issue you can put a deepcopy of your transformations to the workflow and then run fit. That way you will be able to run your workflow.fit multiple times.
Here is a function I'm using:
```py
from copy import deepcopy
def nvt_exec(df, columns):
    columns = deepcopy(columns)
    df_event = nvt.Dataset(df) 
    workflow = nvt.Workflow(columns)
    workflow.fit(df_event)                              #without deep copy it will fail here 
    return workflow.transform(df_event).to_ddf().compute() 
```

**Comment by jperez999** [comment]
@PiotrCzapla great catch. Sorry about the late response.
