### ISSUE TITLE
[BUG] The cpu execution categorical ops seems to take 16x slower pd.Categorical

### ISSUE THREAD

**Issue by PiotrCzapla** [NVIDIA-Merlin/NVTabular#1246]
**Describe the bug**
I'm evaluating NVTabular to see how much time am I going to save thanks to GPU execution. 
I'm using the  data from Tranformer4Rec workshop (subset of CITERO dataset) 

The execution of NVTabular on cpu is super slow. It takes 58 sec to convert columns to categorical representation while it takes only 1.7 sec on GPU. To double check I've run the same thing in pandas and it took only 3.5 sec. 
The execution is so solve I've though It might be considered a bug.

**Steps/Code to reproduce bug**
load the data
```py
import os

import numpy as np 
import cupy as cp
import glob

import cudf
import nvtabular as nvt
from nvtabular import ColumnSelector

from copy import deepcopy
def nvt_exec(df, columns, cpu=False):
    columns = deepcopy(columns)
    df_event = nvt.Dataset(df, cpu=cpu) 
    workflow = nvt.Workflow(columns)
    workflow.fit(df_event)                       
    return workflow.transform(df_event).to_ddf().compute()

INPUT_DATA_DIR = os.environ.get("INPUT_DATA_DIR", "/dli/task/data/")
df = cudf.read_parquet(os.path.join(INPUT_DATA_DIR, 'Oct-2019.parquet'))  

cpu_df = df.to_pandas()

# categorify features 
cat_cols = ['user_session', 'category_code', 'brand', 'user_id', 'product_id', 'category_id', 'event_type'] 
cat_feats = cat_cols >> nvt.ops.Categorify(start_index=1)
```
run the code on cpu
```
%time nvt_exec(cpu_df, cat_feats, cpu=True).head()
CPU times: user 44.5 s, sys: 16.6 s, total: 1min 1s
Wall time: 1min
```

Run similar code in pandas
```
%time pd.DataFrame({c:pd.Categorical(cpu_df[c]) for c in cat_cols})
CPU times: user 3.08 s, sys: 444 ms, total: 3.52 s
Wall time: 3.52 s
```
For comparison the same on GPU is 2x fsater than pandas
```
%time nvt_exec(df, cat_feats, cpu=False).head()
CPU times: user 993 ms, sys: 643 ms, total: 1.64 s
Wall time: 1.68 s
```

**Expected behavior**
The  speed of execution of cpu version of nvt should match pandas.

**Environment details (please complete the following information):**
 - Environment location: docker on aws
 - Method of NVTabular install: not sure it is a vm from the Transformers4Rec gtc workshop

**Comment by EvenOldridge** [comment]
Our CPU back end is mapped via Dask dispatch to pandas equivalent commands at the data frame operation level.  

The optimized versions of these functions are likely to be much faster, but for the sake of flexibility and supporting udfs we don't do any mapping to custom versions 

For us to do our own dispatch for specific functions isn't feasible currently, but could be something we consider in the future.

**Comment by EvenOldridge** [comment]
Closing bug and adding a feature request: https://github.com/NVIDIA-Merlin/NVTabular/issues/1289
