### ISSUE TITLE
[BUG] Fail to call <node>.output_columns.names property even after fitting on a dataset

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA-Merlin/NVTabular#1248]
**Describe the bug**
HugeCTR ecommerce example failed. While triaging the issue, we discovered the above issue.
https://gitlab-master.nvidia.com/vinhn/hugectr/-/blob/ecommerce-bug/notebooks/ecommerce-example.ipynb

**Steps/Code to reproduce bug**

docker run --runtime=nvidia --rm -it --cap-add SYS_NICE -v $(pwd):/hugectr -w /hugectr -p 8888:8888 nvcr.io/nvidia/merlin/merlin-training:21.11

Then run the above notebooks.  After proc.fit, calling cont_feats.output_columns.names will fail with 
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1806/369499645.py in <module>
----> 1 cont_feats.output_columns.names

/nvtabular/nvtabular/workflow/node.py in output_columns(self)
    328     def output_columns(self):
    329         if self.output_schema is None:
--> 330             raise RuntimeError(
    331                 "The output columns aren't computed until the workflow "
    332                 "is fit to a dataset or input schema."

RuntimeError: The output columns aren't computed until the workflow is fit to a dataset or input schema.

```
even though it is clear that we have already called proc.fit().

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 

**Additional context**

**Comment by EvenOldridge** [comment]
@vinhngx is this still an issue?  I'm hoping the examples are fixed?  Please reopen if you're still encountering this.
