### ISSUE TITLE
[BUG]Load criteo model failed in triton inference

### ISSUE THREAD

**Issue by lunachy** [NVIDIA-Merlin/NVTabular#1263]
**Describe the bug**
Load criteo model failed in triton inference.

**Steps/Code to reproduce bug**
1. tritonserver --model-repository=/criteo_hugectr --model-control-mode=explicit
2. triton_client = tritonhttpclient.InferenceServerClient(url="localhost:8000", verbose=True)
3. triton_client.load_model(model_name="criteo")

**Expected behavior**
load criteo model successfully.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of NVTabular install: Docker
   - docker pull nvcr.io/nvidia/merlin/merlin-inference:21.11
   - docker run -itd --gpus=all -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /data:/data nvcr.io/nvidia/merlin/merlin-inference:21.11
   - docker exec -it xxx /bin/bash
   - tritonserver --model-repository=/criteo_hugectr --model-control-mode=explicit
 

**Additional context**
I1122 02:50:54.241694 8240 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8001
I1122 02:50:54.241937 8240 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I1122 02:50:54.282939 8240 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002
I1122 02:51:25.854130 8240 model_repository_manager.cc:1022] loading: criteo_nvt:1
I1122 02:51:25.966985 8240 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: criteo_nvt_0 (CPU device 0)
I1122 02:52:11.779736 8240 model_repository_manager.cc:1183] successfully loaded 'criteo_nvt' version 1
I1122 02:52:11.790670 8240 model_repository_manager.cc:1022] loading: criteo:1
I1122 02:52:11.909641 8240 hugectr.cc:1140] TRITONBACKEND_Initialize: hugectr
I1122 02:52:11.909672 8240 hugectr.cc:1150] Triton TRITONBACKEND API version: 1.6
I1122 02:52:11.909684 8240 hugectr.cc:1156] 'hugectr' TRITONBACKEND API version: 1.6
I1122 02:52:11.909694 8240 hugectr.cc:1181] The HugeCTR backend Repository location: /opt/tritonserver/backends/hugectr
I1122 02:52:11.909704 8240 hugectr.cc:1191] The HugeCTR backend configuration:
{}
I1122 02:52:11.909723 8240 hugectr.cc:311] *****Parsing Parameter Server Configuration from 
I1122 02:52:11.909734 8240 hugectr.cc:313] Fail to open Parameter Server Configuration, please check whether the file path is correct
I1122 02:52:11.909746 8240 hugectr.cc:325] Enable support for Int64 embedding key: 0
I1122 02:52:11.909759 8240 hugectr.cc:329] The depolyment Data base type is: local
I1122 02:52:11.909769 8240 hugectr.cc:335] The depolyment cache_size_percentage_redis is: 
I1122 02:52:11.909781 8240 hugectr.cc:339] Redis ip is: 127.0.0.1:7000
I1122 02:52:11.909784 8240 hugectr.cc:343] Local RocksDB path is: 
I1122 02:52:11.909795 8240 hugectr.cc:433] *****The HugeCTR Backend Parameter Server is creating...*****
I1122 02:52:11.909799 8240 hugectr.cc:446] *****The HugeCTR Backend Backend Parameter Server(Int32) is creating...***** 
Signal (11) received.
 0# 0x000055B26A8A38A9 in tritonserver
 1# 0x00007F7E94B4B210 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# HugeCTR::parameter_server<unsigned int>::parameter_server(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<HugeCTR::InferenceParams, std::allocator<HugeCTR::InferenceParams> >&) in /usr/local/hugectr/lib/libhugectr_inference.so
 3# HugeCTR::HugectrUtility<unsigned int>::Create_Parameter_Server(HugeCTR::INFER_TYPE, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<HugeCTR::InferenceParams, std::allocator<HugeCTR::InferenceParams> >&) in /usr/local/hugectr/lib/libhugectr_inference.so
 4# 0x00007F7E5C043F52 in /opt/tritonserver/backends/hugectr/libtriton_hugectr.so
 5# TRITONBACKEND_Initialize in /opt/tritonserver/backends/hugectr/libtriton_hugectr.so
 6# 0x00007F7E956C2F7B in /opt/tritonserver/bin/../lib/libtritonserver.so
 7# 0x00007F7E956C49FB in /opt/tritonserver/bin/../lib/libtritonserver.so
 8# 0x00007F7E956CD000 in /opt/tritonserver/bin/../lib/libtritonserver.so
 9# 0x00007F7E955739BA in /opt/tritonserver/bin/../lib/libtritonserver.so
10# 0x00007F7E955817B1 in /opt/tritonserver/bin/../lib/libtritonserver.so
11# 0x00007F7E94F39DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
12# 0x00007F7E953B7609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
13# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Segmentation fault (core dumped)

**Comment by yingcanw** [comment]
@benfred  Hi Ben, users also submit a similar issue in hugectr_backend(https://github.com/triton-inference-server/hugectr_backend/issues/23). Users also can't launch tensorflow，onnxruntime，pytorch, openvino backend in merlin-inference:21.11. I also met the same issue about `Not found: unable to load backend library: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block;`. I need to build and install libjemalloc manually and then hugectr_backend is run successfully.

**Comment by benfred** [comment]
This should be fixed now -
