### ISSUE TITLE
[BUG] keyset generation does not support int64 keys.

### ISSUE THREAD

**Issue by jershi425** [NVIDIA-Merlin/NVTabular#1264]
**Describe the bug**
When the embedding key is int64 type, the dumped .keyset file for HugeCTR are wrong.

**Steps/Code to reproduce bug**
Currently I think the writing process is hard-coded into int32: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/nvtabular/io/writer.py#L290

**Expected behavior**
The dumped key type should be consistent with the processed data type.

**Comment by viswa-nvidia** [comment]
retiring this bug
