### ISSUE TITLE
[BUG] package_general_metadata() can't find the categorical columns

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/NVTabular#1266]
**Describe the bug**
I am running into an issue where fitting on the training dataset and then transforming it and saving it is fine, but when I then try to transform + save the validation and test dataset, it fails.  Weirdly, it works when ran step by step in a Jupyter notebook environment, but it errors as a Job when it hits the `to_parquet` call with the following error. 

```
Traceback (most recent call last):
 File "/usr/local/path/to/my/preprocess.py", line 77, in <module>
  main(sys.argv)
 File "/usr/local/path/to/my/preprocess.py", line 73, in main
  cars_preprocessor.preprocess()
 File "/usr/localpath/to/my/preprocessor.py", line 101, in preprocess
  self.fit_transform_features()
 File "/usr/local/path/to/my/preprocessor.py", line 132, in fit_transform_features
  self._transform_and_save(
 File "/usr/local/path/to/my/preprocessor.py", line 249, in _transform_and_save
  self.nvt_workflow.proc.transform(
 File "/nvtabular/nvtabular/io/dataset.py", line 897, in to_parquet
  _ddf_to_dataset(
 File "/nvtabular/nvtabular/io/dask.py", line 369, in _ddf_to_dataset
  out = client.compute(out).result()
 File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/client.py", line 228, in result
  raise exc.with_traceback(tb)
 File "/usr/lib/python3.8/contextlib.py", line 75, in inner
  return func(*args, **kwds)
 File "/nvtabular/nvtabular/io/dask.py", line 210, in _write_subgraph
  return writer.close()
 File "/nvtabular/nvtabular/io/writer.py", line 313, in close
  _general_meta = self.package_general_metadata()
 File "/nvtabular/nvtabular/io/writer.py", line 252, in package_general_metadata
  data["cats"].append({"col_name": c, "index": self.col_idx[c]})
KeyError: 'my_categorical_column1'
```

The line 249 mentioned above in `_transform_and_save` looks like 
```
self.nvt_workflow.proc.transform(dataset).to_parquet(
         output_path=output_path,
         out_files_per_proc=out_files_per_proc,
         shuffle=nvt.io.Shuffle.PER_PARTITION,
         dtypes=self.nvt_workflow.dict_dtypes,
         cats=self.nvt_workflow.final_cat_columns,
         conts=self.nvt_workflow.final_cont_columns,
         labels=self.nvt_workflow.label_cols,
)
```

I have checked that the transformed output looks correct. I have also tried setting a `out_path` in `Categorify()` but that did not have any effect. And it is especially weird because the training set is able to be transformed and saved correctly. In fact, the data itself is written out for the validation set (which I do a `transform` and `to_parquet` right after the training set), but the error comes out right after the data is written out and NVT tries to generate the metadata file for the validation set. 

I have also checked that the variables being passed into `dtypes`, `cats`, `conts`, `labels` are correct. The `my_categorical_column1` is the first item in the `cats`. 

Could you provide guidance on how to debug this issue? I appreciate it a lot - thank you so much!

**Environment details (please complete the following information):**
Docker image built from the latest `merlin-training:21.11` image released

**Comment by EvenOldridge** [comment]
@rnyak This sounds very similar to a problem you were running into.  Any guidance for Shoya?

**Comment by rnyak** [comment]
@shoyasaxa Are you running any of our example notebooks and getting this error? if yes which one? if no, can you please add a simple reproducibility example with a synthetic dataset? Thanks.

**Comment by shoyasaxa** [comment]
Hi @rnyak! I am not running any of the example notebooks. I will try to create a synthetic dataset, but it may be hard. In the mean time, if any of the stack traces point to something wrong I may be doing - please let me know!

**Comment by rnyak** [comment]
@shoyasaxa I am more interested in your ETL workflow script. It is hard to see what you are doing exactly in the stack above.
 Can you provide a simple example code with your ETL pipeline? I need to see how you define the ops. And a simple small fake pandas or cudf dataset with 1-2 cats and conts columns would work I believe.

is the `dataset` in the `self.nvt_workflow.proc.transform(dataset)` the validation set? 

Also, I am not sure how you define `self.nvt_workflow.final_cat_columns, self.nvt_workflow.final_cont_columns, self.nvt_workflow.label_cols` ? Note that, you wont get the final output column names from a workflow if you do not fit the workflow yet.

**Comment by shoyasaxa** [comment]
Hi @rnyak, after extensive testing, I found out that my `out_files_per_proc` I was passing into the `to_parquet` call was too big. Reducing it solved the problem. It is still peculiar how this worked in Jupyter notebook and not when ran as a job though.

**Comment by shoyasaxa** [comment]
So I think NVT somehow had a problem splitting up the validation dataset into 160 files (I set `out_files_per_proc` to 40 for this one, and I am using 4 GPUS so 40*4 = 160), though it had no problem splitting up and saving  the training dataset into 400 files. I think the error was saying “hey I saw this`my_categorical_column1 ` column in all of your other parquet part files, but I don’t see any for these last X files you want me to write out." 

I understand why this would be an issue if our dataset was 159 rows and asking it to split it into 160 files, but that is not the problem here.

**Comment by EvenOldridge** [comment]
@rjzamora can you take a look?

**Comment by rjzamora** [comment]
Note that @jperez999 may have resolved this issue in #1301

@shoyasaxa - When you get some free time, could you let us know if you still have problems on the latest `main` branch?

**Comment by benfred** [comment]
@shoyasaxa - going to close this, let me know if this is still a problem

**Comment by shoyasaxa** [comment]
My apologies I missed this - and yes please feel free to close. Thank you!
