### ISSUE TITLE
[BUG] Import problem export_pytorch_ensemble()

### ISSUE THREAD

**Issue by CrustaceanJ** [NVIDIA-Merlin/NVTabular#1273]
Getting the following error while running `export_pytorch_ensemble()`

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_20990/3153831452.py in <module>
----> 1 from nvtabular.inference.triton import export_pytorch_ensemble

~/miniconda3/envs/nvtabular_dev_11.0/lib/python3.8/site-packages/nvtabular/inference/triton/__init__.py in <module>
     30 from tritonclient.utils import np_to_triton_dtype  # noqa
     31 
---> 32 import nvtabular.inference.triton.model_config_pb2 as model_config  # noqa
     33 from nvtabular.columns import Schema  # noqa
     34 from nvtabular.dispatch import _is_list_dtype, _is_string_dtype, _make_df  # noqa

ModuleNotFoundError: No module named 'nvtabular.inference.triton.model_config_pb2'
```
Found that file `nvtabular.inference.triton.model_config_pb2` ​is in repo's `.gitignore` file.

**Environment details (please complete the following information):**
 - Python: 3.8.12
 - OS: Ubuntu 18.04.3 LTS
 - Method of NVTabular install: conda, using file from this repo: `conda/environments/nvtabular_dev_cuda11.0.yml`

**Comment by rnyak** [comment]
@CrustaceanJ which example notebook are you running? can you run the following in your terminal, before running the example?
```
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='python' 
```
Let us know if that solves your issue.


Besides, the recommended way to use Nvidia Merlin would be via docker images? If you want to use docker image you can do the following:
```
docker pull nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11   # current latest container
docker run -it --gpus all -p 9999:8888 -p 9797:9998 -p 9796:8777 --ipc=host nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11 
cd /nvtabular
pip install torch==1.10.0
jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''
```

**Comment by rnyak** [comment]
@CrustaceanJ did you solve the issues based on the instructions above?

**Comment by benfred** [comment]
@CrustaceanJ - going to close, let me know if this is still an issue
