### ISSUE TITLE
[BUG] graph visualization bug

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA-Merlin/NVTabular#1275]
**Describe the bug**
in the movie lens dataset, when I want to simply duplicate a columns, say userID,  the graph visualization of that workflow looks strange, with a node named ['u','s','e','r','I','D']
![image](https://user-images.githubusercontent.com/7205508/143795312-1295fa21-07e8-49d1-b7be-bb5a330406d5.png)

the output is what I expect though
![image](https://user-images.githubusercontent.com/7205508/143795324-4030f329-abce-48e6-8819-a7d9e0855647.png)

**Steps/Code to reproduce bug**
A notebook is available from
/home/scratch.vinhn_sw/NVTab-multi-modal-data-movielens/examples/multi-modal-data-movielens/06-ETL-with-NVTabular-Copy1.ipynb

**Expected behavior**

Node should be named appropriately as 'userId_duplicate'

**Environment details (please complete the following information):**
 Merlin training docker v21.11
nvcr.io/nvidia/merlin/merlin-training:21.11

**Additional context**

**Comment by karlhigley** [comment]
Fixed in https://github.com/NVIDIA-Merlin/core/pull/25
