### ISSUE TITLE
[BUG] No module named py error after importing from git

### ISSUE THREAD

**Issue by arunslb123** [NVIDIA-Merlin/NVTabular#1283]
I installed the library through the following commands
```
git clone https://github.com/NVIDIA-Merlin/NVTabular.git
cd NVTabular
pip install -e .
```

After that I tried importing the library and getting the following error.

![image](https://user-images.githubusercontent.com/3520124/144141548-d0675ec2-d4d0-4f7d-84c0-88cd59f8b3ce.png)

**Comment by rnyak** [comment]
@arunslb123 Can you please provide details about your env? Is it a conda env? are you using a docker container?  If yes which one?

what are your cuda driver and cuda toolkit versions? (you can copy here the `nvidia-smi` and `nvcc --version` commands' print outs.)

**Comment by arunslb123** [comment]
Hi Ronay, 

Steps to reproduce the above issue. 

1) create a conda env using this file https://github.com/NVIDIA-Merlin/NVTabular/blob/main/conda/environments/nvtabular_dev_cuda11.2.yml

2) Update NVTabular from github

git clone https://github.com/NVIDIA-Merlin/NVTabular.git
cd NVTabular
pip install -e .

3) Try import nvtabular as nvt, and you may get no module found error.
![image](https://user-images.githubusercontent.com/3520124/144152007-daac11f8-dffc-460f-9204-d5e8028f9a23.png)

**Comment by rnyak** [comment]
@arunslb123 thanks for the details. The instructions you followed also tells to do the following (not sure if that's the reason):
"When opening a notebook, be sure to select `nvt` from the `Kernel->Change Kernel` menu"

These commands might help to run NVT + TF4Rec in conda env:

1. `conda create -n rapids-21.10 -c rapidsai -c nvidia -c conda-forge rapids=21.10 python=3.8 cudatoolkit=11.2` #install rapids, change the python and cudatoolkit versions based on your system
2. `conda activate rapids-21.10` 
3. `git clone https://github.com/NVIDIA-Merlin/NVTabular.git`
4. `cd NVTabular` && `pip install -e . `  #install NVT
4. `git clone https://github.com/NVIDIA-Merlin/Transformers4Rec.git`
5. `cd Transformers4Rec/requirements` && `pip install -r base.txt` && `pip install torch==1.10.0` && `pip install torchmetrics==0.3.2`
6. `cd Transformers4Rec` and  `pip install -e .`

if extra libraries required you can install them base on  [dev.txt](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/requirements/dev.txt)

**Comment by benfred** [comment]
@arunslb123 what version of python are you using? I think this issue is caused by a recent change that breaks on python 3.7 

@jperez999 In your PR here https://github.com/NVIDIA-Merlin/NVTabular/commit/93d79c4a2 , can we eliminate the check for PathBase ?

**Comment by benfred** [comment]
We're removing the reference to the py PathBase code
