### ISSUE TITLE
[DOC] Correct README for Running Example Notebooks

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1286]
**Describe the bug**

![image](https://user-images.githubusercontent.com/73861554/144324603-85e7f6e9-61e6-4949-b804-d7ed0bef9aae.png)
**NOTES** in [README for Running Example Notebooks ](https://github.com/NVIDIA-Merlin/NVTabular/tree/main/examples#running-the-example-notebooks) mention 

> If you are running Getting Started with MovieLens , Advanced Ops with Outbrain or Tabular Problems with Rossmann example notebooks you need to add -v ${PWD}:/root/ to the docker script above

but adding the `-v ${PWD}:/root/` results in `ModuleNotFoundError: No module named 'nvtabular'`.

Also just want to highlight that Step 2 
![image](https://user-images.githubusercontent.com/73861554/144324933-d4a93073-166c-46a3-8b3d-f82cb4b6d63a.png)

says to install Jupyter-Lab but that's unnecessary for all the Merlin containers except for Merlin-Inference because they already come installed with JupyterLab so maybe making a note of that would be helpful for new users.

**Comment by kshitizgupta21** [comment]
Please add to the README the right docker run command with appropriate flags for mounting for launching the Merlin-Tensorflow container for running 03-Training-with-TF notebook.ipynb in `getting-started-movielens`.  Currently, if we follow the README and add the `-v ${PWD}:/root/` to docker run like so `docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host -v ${PWD}:/root/ <docker container> /bin/bash` it results in `ModuleNotFoundError: No module named 'nvtabular'`. 

We definitely need to launch the Merlin TF container in way so that the TF model generated in 03-Training-with-TF notebook is persisted once we exit the Merlin Tensorflow container and is accessible inside the Merlin Inference container when we want to run 04-Triton-Inference-with-TF.ipynb

**Comment by kshitizgupta21** [comment]
The same issue of disconnect between model training notebook and triton inference notebook happens when trying to do inference for HugeCTR model in [`scaling_criteo`](https://github.com/NVIDIA/NVTabular/tree/main/examples/scaling-criteo) notebook [04-Triton-Inference-with-HugeCTR.ipynb](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb). 

The user is not given the right docker run command when they launch the Merlin Training (HugeCTR) container which can allow them to persist the trained HugeCTR model in `/criteo_hugectr/1` on local system. And we also don't have the the right docker run command for launching Merlin Inference container to run [04-Triton-Inference-with-HugeCTR.ipynb](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb) notebook. The notebook itself doesn't contain any docker run command and again the docker run command given in README also doesn't work. Notably, the triton inference notebook expects the trained HugeCTR model to exist in `/criteo_hugectr/1` directory but of course we lose access to that directory as soon as we exit out of Merlin Training container and leave the Train hugeCTR notebook. This is why for both of these notebooks 03-Training-with-HugeCTR.ipynb and 04-Triton-Inference-with-HugeCTR.ipynb we need the right docker run commands with right flags for mounting local system directories to allow the user to actually run the training and inference workflow.

Because of this issue I wasn't able to test Triton Inference for trained HugeCTR model for the criteo dataset.

**Comment by rnyak** [comment]
@albert17  can you check that out? Thanks.

**Comment by albert17** [comment]
@kshitizgupta21 @rnyak I will check and fix as needed

**Comment by viswa-nvidia** [comment]
Closing this based on last comment
