### ISSUE TITLE
[BUG] Criteo TensorFlow examples does not use numerical features

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/NVTabular#1315]
**Describe the bug**
Numeric Inputs in TensorFlow example for scaling criteo are not used in the next layers

**Comment by EvenOldridge** [comment]
@bschifferer is this still a valid issue?  Can you provide more details?

**Comment by bschifferer** [comment]
@rvk007 created a PR to update the TensorFlow model with Merlin Models. I need to review it, but I think we will fix the issue soon

**Comment by bschifferer** [comment]
We updated the example to use merlin models (in Merlin/Merlin repo)
