### ISSUE TITLE
[BUG] NVTabular and torch.masked_select cause each other failed.

### ISSUE THREAD

**Issue by YKX-A** [NVIDIA-Merlin/NVTabular#1327]
**Describe the bug**
CASE 1
```python
1. run PyTorch's `masked_select` function and backward, success ✅
2. run NVTabular snippet, failed ❌
```

and in another order. CASE 2:
```python
1. run NVTabular snippet, success ✅
2. run PyTorch's `masked_select` function and backward, failed ❌
```

**Steps/Code to reproduce bug**
(`environment.yml`: https://github.com/YKX-A/debug_nvt_pt/blob/main/environment.yml)

```shell
conda env create -n debug_nvt_pt -f environment.yml
conda activate debug_nvt_pt
```

- import and definition section
```python

import numpy as np
import nvtabular as nvt
from nvtabular import Workflow, ops

import os 
import torch
import torch as t

print(nvt.__version__)

bsz = 8
ebd_dim = 32

# ========== to trace the error ==========
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
torch.autograd.set_detect_anomaly(True)


def run_nvtabular_snippet():
    gdf_test = nvt.dispatch._make_df(
        {
            "ad_id": [1, 2, 2, 6, 6, 8, 3, 3],
            "source_id": [2, 4, 4, 7, 5, 2, 5, 2],
            "platform": [1, 2, np.nan, 2, 1, 3, 3, 1],
            "cont": [1, 2, np.nan, 2, 1, 3, 3, 1],
            "cont2": [10, 90, np.nan, 20, 10, 30, 30, 10],
            "clicked": [1, 0, 1, 0, 0, 1, 1, 0],
        }
    )

    cats = ["ad_id", "source_id", "platform"]
    cat_features = cats >> ops.Categorify() >> ops.Rename(postfix='_log')


    cont_features = ["cont", "clicked", "cont2"] >> ops.FillMissing()
    rename = cont_features[["cont"]] >> ops.Normalize() >> ops.Rename(
        postfix='_rename_cont')

    p = Workflow(cat_features + cont_features + rename)
    p.fit_transform(nvt.Dataset(gdf_test)).to_ddf().compute()


def run_torch_backward_with_masked_select_operation():

    
    # ========== forward ==========
    a = t.nn.Linear(ebd_dim, ebd_dim).cuda()
    ipt = t.randn(bsz, ebd_dim).cuda()
    res = a(ipt)
    random_mask = (t.rand(bsz) > 0.5).cuda()
    
    res2 = t.masked_select(res, random_mask.unsqueeze(1))  # use masked_select
    
    loss = res2.sum()
    
    # ========== backward ==========
    
    print('before backward')
    print(loss)
    loss.backward()
    print('backward finished ')

def run_torch_backward_with_substituted_masked_select():
    # ========== forward ==========
    a = t.nn.Linear(ebd_dim, ebd_dim).cuda()
    ipt = t.randn(bsz, ebd_dim).cuda()
    res = a(ipt)
    random_mask = (t.rand(bsz) > 0.5).cuda()
    
    idx = (random_mask == True).nonzero().squeeze(-1)  # substitute masked_select
    res2 = t.index_select(res, 0, idx)
    
    loss = res2.sum()
    
    # ========== backward ==========
    print(loss)
    print(t.masked_select(res, random_mask.unsqueeze(1)).sum())
    print('before backward')
    loss.backward()
    print('backward finished ')
```

- Case 1: `RuntimeError: scan failed on 2nd step: cudaErrorInvalidValue: invalid argument`
```python
run_nvtabular_snippet()  # ✅
run_torch_backward_with_masked_select_operation()  # ❌
```

- Case 2 (before run, reopen the python interpreter/ retrart the kernel)  
`RuntimeError: CUDA error encountered at: ../include/cudf/detail/null_mask.cuh:326: 101 cudaErrorInvalidDevice invalid device ordinal`:
```python
run_torch_backward_with_masked_select_operation()  # ✅
run_nvtabular_snippet()  # ❌
```

Further description:
If we run `run_nvtabular_snippet` or `run_nvtabular_snippet` seperately (e.g, in a new kernel), there is no problem here.
I doubt the problem is on the `torch.masked_select` operator, which causes the `backward()` to fail when I have run some NVTabular code before.

Inversely, I can backward through `torch.masked_select`, but then I would failed in `run_nvtabular_snippet`.

A wordaround towards this problem is that we avoid using `torch.masked_select` and find an alternative:
(suppose we are in a clean kernel)

- wordaround
```python
# for case 1
run_torch_backward_with_substituted_masked_select()  # ✅
run_nvtabular_snippet()  # ✅

# for case 2
run_nvtabular_snippet()  # ✅
run_torch_backward_with_substituted_masked_select()  # ✅
```

**Expected behavior**
They shouldn't affect each other, right?

**Environment details (please complete the following information):**
- all packages are installed via conda
- `environment.yml`: https://github.com/YKX-A/debug_nvt_pt/blob/main/environment.yml
 

**Additional context**
- Ubuntu 18.04.5 LTS
- GPU: GTX 2080TI

**Comment by benfred** [comment]
I think this might be caused by this issue in pytorch: https://github.com/pytorch/pytorch/issues/52663#issuecomment-803642518

 In our docker container we've shipped a version of pytorch that is compiled with ```-Xcompiler -fno-gnu-unique``` - which should fix this issue.

Can you try this out on our latest pytorch training container (```docker pull nvcr.io/nvstaging/merlin/merlin-pytorch-training:21.12```)  and see if that resolves?

**Comment by YKX-A** [comment]
@benfred things seem to work fine in `docker nvcr.io/nvstaging/merlin/merlin-pytorch-training:21.12`, except that I have to run ` conda install -c conda-forge cudatoolkit=11.2 cupy` to fix an error raised by cupy.

cupy's error is as follow.
```python
cupy/cuda/function.pyx in cupy.cuda.function.Module.load()

cupy/cuda/function.pyx in cupy.cuda.function.Module.load()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.moduleLoadData()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.check_status()

CUDADriverError: CUDA_ERROR_UNSUPPORTED_PTX_VERSION: the provided PTX was compiled with an unsupported toolchain.
```

related to https://github.com/cupy/cupy/issues/5095;
probably caused by my incompatible CUDA Build Version, CUDA Driver Version and CUDA Runtime Version
```python
python -c "import cupy; cupy.show_config()"
...
CUDA Build Version           : 11040
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11050
...
```

after being reinstalled, my version is :
```python
...
CUDA Build Version  : 11020
CUDA Driver Version : 11020
CUDA Runtime Version : 11020
...
```

**Comment by benfred** [comment]
Thanks for verifying @YKX-A !  Can you run ```nvidia-smi``` and paste the output here ?

@albert17 you've seen the ```the provided PTX was compiled with an unsupported toolchain``` error before right? Is this going to be fixed in the next version of our containers?

**Comment by YKX-A** [comment]
> Thanks for verifying @YKX-A ! Can you run `nvidia-smi` and paste the output here ?
> 
> @albert17 you've seen the `the provided PTX was compiled with an unsupported toolchain` error before right? Is this going to be fixed in the next version of our containers?

My output in the docker is:
```shell
root@9cefda1b22a5:/workspace# nvidia-smi
Fri Dec 31 01:23:39 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:26:00.0 Off |                  N/A |
|  0%   39C    P8    24W / 280W |     43MiB / 11016MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by albert17** [comment]
Hi @YKX-A

If you update the driver you should be able to stop seeing this error.

Please try 510.00+

**Comment by YKX-A** [comment]
Thanks, @albert17
