### ISSUE TITLE
[QST] Does NVTabular support running on Spark?

### ISSUE THREAD

**Issue by leiterenato** [NVIDIA-Merlin/NVTabular#1328]
**What is your question?**
Does NVTabular support running on Spark?

I'd like to run NVTabular at scale on a Spark cluster.
Is NVTabular capable of leverage the benefits of Spark to execute on GPUs? 
If yes, is there any documentation on how to do it?

**Comment by benfred** [comment]
No - this isn't something that we support right now.  We're using dask-cudf to distribute work among workers, and don't have any spark integration at the moment.

There is a project https://nvidia.github.io/spark-rapids/ that lets you use cudf with spark, but we haven't looked into integrating it with nvtabular yet.
