### ISSUE TITLE
[DOC] Confusing text for HugeCTR data types in 02-ETL-with-NVTabular Movielens example notebook

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1331]
## Report incorrect documentation

**Location of incorrect documentation**
[Provide links and line numbers if applicable.](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb)

**Describe the problems or issues found in the documentation**
02-ETL-with-NVTabular notebook says we pass in hugectr datatypes when creating the dataset but we don’t actually do that which is confusing to a new user. 

![image](https://user-images.githubusercontent.com/73861554/146286251-d6f5f775-194b-4bfe-b483-ccae142437eb.png)

In reality, we pass in hugectr dictionary of datatypes later when we transform the workflow. 

**Suggested fix for documentation**
Make text around passing in hugeCTR datatypes dictionary less confusing.

**Comment by albert17** [comment]
@kshitizgupta21 Thanks for the feedback.

As you are pointing, that description should be updated. I will include it in PR #1329
