### ISSUE TITLE
[BUG] Incorrect shell commands and variables for creating output folders in Movielens 03-Training-with-HugeCTR Example Notebook

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1332]
**Describe the bug**
In this code cell for creating output folder for models, we have incorrect variables and shell commands
<img src="https://user-images.githubusercontent.com/73861554/146286700-80982bd7-9f47-4d35-aff9-d41b5c3aef3d.png" width="600" height="120">

Firstly, based on the `MODEL_BASE_DIR = os.environ.get("MODEL_BASE_DIR", os.path.expanduser("~/nvt-examples/"))` that we define in a few cells above, it appears to me we would want `MODEL_DIR` to be subdirectory of `MODEL_BASE_DIR` otherwise I don't see the point of defining a `MODEL_BASE_DIR`. So I believe it should be `MODEL_DIR = os.path.join(MODEL_BASE_DIR, "model/movielens_hugectr/")`

Secondly, in the second line `!rm -r MODEL_DIR` I don't understand why we are trying to delete a directory that we haven't even created yet. This is why the user gets the error: `rm: cannot remove 'MODEL_DIR': No such file or directory`
<img src="https://user-images.githubusercontent.com/73861554/146287230-baf482e4-d54c-4f97-bb38-a0d4ba428642.png" width="600" height="120">

Lastly, in the third line we try to create the `MODEL_DIR` and its subdirectory `1` but it's the wrong shell command because it results in 3 subdirectories namely, `MODEL_DIR`, `1` and `+`
<img src="https://user-images.githubusercontent.com/73861554/146287558-b28acd46-f714-4930-ac2d-71b118244975.png" width="350" height="300">

I believe the right shell command here would be `mkdir -p $MODEL_DIR/1` which includes the `$` prefix so that shell can understand python variables.

**Environment details (please complete the following information):**
 - Environment location: Docker Merlin Training 21.12 container running on DGX Station V100 16GB

**Comment by albert17** [comment]
Hi @kshitizgupta21 

Thanks for posting the errors. There is a PR #1329 that addresses them among some other thing.

Please, feel free to add any comment there.
