### ISSUE TITLE
[DOC] Incorrect and confusing documentation for Solver in Movielens 03-Training-with-HugeCTR Example Notebook

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1333]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb

**Describe the problems or issues found in the documentation**
![image](https://user-images.githubusercontent.com/73861554/146288935-2fe051c6-56cc-40ab-a85a-d66e5cfa2031.png)
Incorrect punctuation results in very confusing documentation for new user for `vvgpu` in `CreateSolver`. Notably, it says For example: [[0,1],[1,2]] indicates that two nodes are used in the first node. GPUs 0 and 1 are used while GPUs 1 and 2 are used for the second node. 

I believe it should instead be:

For example: [[0,1],[1,2]] indicates that two nodes **are used.** **In the first node, GPUs 0 and 1** are used while GPUs 1 and 2 are used for the second node. 

Furthermore, in the same notebook cell we also have the documentation for `max_eval_batches` and `batchsize_eval` args and it's exactly same which is wrong. 
![image](https://user-images.githubusercontent.com/73861554/146289569-50c5eda4-d759-49fe-a394-9799fd0cc55e.png)

**Steps taken to verify documentation is incorrect**
Looked at the [correct documentation for `CreateSolver` method ](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/python_interface.md#createsolver-method) in HugeCTR github

**Comment by albert17** [comment]
@kshitizgupta21 Thanks for checking with HugeCTR repo

I will include those changes in #1329 too
