### ISSUE TITLE
[DOC] Add docker run command mounting /raid for Criteo Example Notebooks to the Examples README

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/NVTabular#1335]
## Report needed documentation

**Report needed documentation**
Currently, in the examples [README](https://github.com/NVIDIA-Merlin/NVTabular/tree/main/examples) the user is told to use the following docker run command to launch notebooks.
```
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host <docker container> /bin/bash
``` 

But the scaling_criteo notebooks, starting with the very first cell in [01 Download Convert notebook](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/01-Download-Convert.ipynb), all expect `BASE_DIR` to be `/raid` as seen below:
![image](https://user-images.githubusercontent.com/73861554/146321544-1e24f9ee-220e-4c24-b407-7de4673516ce.png)

**Describe the documentation you'd like**
Add docker run with appropriate mounting of `/raid` like so in the README for running Criteo Example Notebooks. For example,

`docker run --gpus=all -v /mnt/raid:/raid -w /nvtabular --cap-add SYS_NICE --rm -it -p 8321:8321 --ipc=host ${IMAGE}  /bin/bash`

Finally, I think if the criteo examples expect the user to use `/raid` then it would be very helpful for cloud users if you could link the [instructions for creating RAID volume](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/docs/source/resources/cloud_integration.md) with this appropriate docker run command. Currently, those instructions are hidden away in a folder but seeing as how Criteo Examples notebooks all use the `/raid` it would be useful to mention these creating raid volume instructions in their context.

**Comment by albert17** [comment]
@kshitizgupta21 

The folder name could be set by the user to point wherever they have the data. 

You can use a storage system that it is RAID or it is not, definitely you will get better performance with RAID as explained.

It is possible to add the mounting option to the docker command, and link the cloud configuration description, but not sure if appropriated as a generic example. 

@jperez999 what do you think?

**Comment by jperez999** [comment]
So /raid is just the data directory, that is the name we give it. The current standard for storage is NVMe Drives. Here are some tips for cloud setup: https://github.com/NVIDIA-Merlin/NVTabular/blob/82ace00bf5241fe2b2c292394aed9542e6e23c4e/docs/source/resources/cloud_integration.md

**Comment by viswa-nvidia** [comment]
@kshitizgupta21 , please review and confirm closure.

**Comment by kshitizgupta21** [comment]
we can close the issue.
