### ISSUE TITLE
[BUG] Missing Dependency `pynvml`

### ISSUE THREAD

**Issue by SimonCW** [NVIDIA-Merlin/NVTabular#1341]
**Describe the bug**
The package `pynvml` is missing from the dependencies.

**Steps/Code to reproduce bug**
- Installing  nvtabular=0.8  and cudatoolkit=11.0
- Running https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb
- Upon Dataset instantiation fails with `No module named 'pynvml'` while calling `_pynvml_mem_size()` in `utils.py`

**Expected behavior**
`pynvml` should be installed as a dependency of nvtabular

**Environment details (please complete the following information):**
 - Environment location: [Docker]
 - Method of NVTabular install: [conda, Docker]

**Comment by benfred** [comment]
Thanks for the bug report Simon! Glad to see you giving NVTabular a try.

How did you install nvtabular? Was it through conda or pip? 

Also, Can you run the following and tell me what it reports?
```
import numba.cuda
print(numba.__version__)
print(numba.cuda.current_context().get_memory_info())
```

I don't think that we should be directly depending on pynvml, its currently only used as a backup method if we can't get the GPU memory from ```numba.cuda```:

https://github.com/NVIDIA-Merlin/NVTabular/blob/22df264c3b36514755492879aa1a1d8e7732e235/nvtabular/utils.py#L70-L79

I'm thinking we should probably remove this backup method entirely and not depend on pynvml at all, but to do that we need to make sure that we can rely on the implementation from numba. 

@rjzamora what do you think?

**Comment by SimonCW** [comment]
Hey @benfred, 

I installed via Conda in a Docker and I am running on a Kubeflow Cluster.

I did some further investigation, the problem seems to be that `import nvtabular` messes up `numba.cuda.current_context()`

Running this:
```python
import numba.cuda
import nvtabular as nvt

print(numba.__version__)
print(numba.cuda.current_context().get_memory_info())
```
Results in the NotImplementedError which leads to the fallback to pynvml:
```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/tmp/ipykernel_767/2083043560.py in <module>
      2 
      3 print(numba.__version__)
----> 4 print(numba.cuda.current_context().get_memory_info())

/opt/conda/envs/jovyan_env/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in get_memory_info(self)
   1246         """Returns (free, total) memory in bytes in the context.
   1247         """
-> 1248         return self.memory_manager.get_memory_info()
   1249 
   1250     def get_active_blocks_per_multiprocessor(self, func, blocksize, memsize,

/opt/conda/envs/jovyan_env/lib/python3.8/site-packages/rmm/rmm.py in get_memory_info(self)
    147 
    148     def get_memory_info(self):
--> 149         raise NotImplementedError()
    150 
    151     @property

NotImplementedError: 
```

But running (after Kernel restart of course):
```python
import numba.cuda
print(numba.__version__)
print(numba.cuda.current_context().get_memory_info())
import nvtabular as nvt
```
Gives (no `pynvml` needed):
```python
0.55.0rc1
MemoryInfo(free=11523588096, total=16945512448)
```

The problem is in the `memory_manager` attribute.

In the failing case this:
```python
ctx = numba.cuda.current_context()
ctx.memory_manager
```
is of type `rmm.rmm.RMMNumbaManager whereas without importing `nvtabular` first, the manager is of type `numba.cuda.cudadrv.driver.NumbaCUDAMemoryManager` ... nasty 😀.

**Comment by viswa-nvidia** [comment]
@rjzamora , please take a look
