### ISSUE TITLE
[BUG] Dependency pinning might be too strict

### ISSUE THREAD

**Issue by SimonCW** [NVIDIA-Merlin/NVTabular#1344]
**Describe the bug**
It is hard to install nvtabular and cuda enabled pytorch at the same time when using conda.

**Steps/Code to reproduce bug**
``` bash
mamba create -n test-nvtab -c nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.7 cudatoolkit=11.0 pytorch
```
This always ends up picking a CPU version of pytorch:
```bash
pytorch                         1.10.0  cpu_py37hf3cc979_0                conda-forge/linux-64      48 MB
```
I tried to install a fitting pytorch build, i.e. :
```bash
 mamba create -n test -c nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.7 cudatoolkit=11.0 "pytorch==1.10.0=cuda110py38hf84197b_0"
```
but this results in:
```bash
Encountered problems while solving:
  - package pytorch-1.10.0-cuda110py38hf84197b_0 requires cudnn >=8.2.1.32,<9.0a0, but none of the providers can be installed
```

**Expected behavior**
Installing nvtabular and pytorch witch cuda enabled for both. 
 

**Additional context**
I wasn't sure whether to put it as a bug or as a feature request, and I am aware that the problem is not necessarily on the NVTabular side, but solving this would make "getting started" with nvtabular much easier IMHO. I ended up installing pytorch via pip and didn't have any problems with training on GPU, which leads me to the suspicion that somewhere the dependency pinning is a bit too strict.

**Comment by viswa-nvidia** [comment]
this should be fixed now. Thanks for reporting .
