### ISSUE TITLE
[QST] Categorify reverse mapping of the categories

### ISSUE THREAD

**Issue by Ahanmr** [NVIDIA-Merlin/NVTabular#1381]
I couldn't find documentation to get the reverse mapping from categorical features back to original strings. I'm currently using nvtabular.ops -> Categorify and using it to label encode (categorize) the data into integers but after the model is trained and predictions are outputted, it's still the label encoded outputs. Is there a way to finding the mapping back to the original strings? Such as 36 -> "4au27365" and 38 -> "8ak68838" etc. What should I do to store this mapping to reverse it back to the original form?

**Comment by Ahanmr** [comment]
@rnyak any suggestions?

**Comment by rnyak** [comment]
@Ahanmr when you use `categorify` op, there is a `categories` folder generated on your system, and the unique mapping parquet files are also stored there. You can easily use these parquet files to see the mapping between encoded and original categorical values.

**Comment by rnyak** [comment]
@Ahanmr do you still have question on that issue? If no, can we close it?

**Comment by Ahanmr** [comment]
Yes, that helped! Thank you very much @rnyak
