### ISSUE TITLE
[BUG] NVTabular ETL multi-GPU breaks, if datatypes for column changes

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/NVTabular#1392]
**Describe the bug**
If I run the multi-GPU NVTabular ETL workflows, they throw errors, when datatype of a column changes.

Examples
Movielens: `Exception: "TypeError('Improperly matched output dtypes detected in rating, float64 and int8')"`
Criteo: `Exception: "TypeError('Improperly matched output dtypes detected in C1, int64 and int32')"`

**Steps/Code to reproduce bug**
Run multi-GPU Movielens: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb
Run criteo: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb 

**Environment details (please complete the following information):**
- merlin-tensorflow-training:22.02 with latest main branch 
 
**Additional information:**
- I tested single-GPU movielens and it worked.
- I changed the single-GPU movielens example to use multi-GPUs and then it breaks
- if I change `ratings = nvt.ColumnSelector(["rating"]) >> nvt.ops.LambdaOp(lambda col: (col > 3.0).astype("int8"))` to `ratings = nvt.ColumnSelector(["rating"])`, then multi-GPU movielens works as well

**Comment by bschifferer** [comment]
I still have the issue for criteo dataset.

I used latest nightly container
I updated nvtabular+core to latest main branch in nightly container

**Comment by bschifferer** [comment]
I get the error even without multi-GPU for the criteo dataset.

**Comment by jperez999** [comment]
@bschifferer please make sure to run the full suite of notebooks when verifying this resolution in the scaling-criteo example. You need to ensure you are running from notebook 01. Your error, is because of an older version of nvtabular that is missing data in the schema of the output criteo parquet dataset from notebook 1 in the example.
