### ISSUE TITLE
[FEA] Create an op to drop unwanted column based on their `nunique` values

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1401]
**Is your feature request related to a problem? Please describe.**

We are working on a dataset and  there are columns where their cardinality is 1. We want to drop these columns (vey common practice). Currently we use a function to do so:

```
def reduce_features(df):
    RMV = []
    for c in df.columns[1:]:
        if df[c].nunique()<=1:
            RMV.append(c)
    df.drop(RMV,axis=1,inplace=True)
    return
```
However, with large dataset we get OOM issue with cuDF so we have to use pandas instead which takes too long. It'd be useful to incorporate an OP in NVTabular.  

If there is a way to do it with NVT other than creating  a new op , I'd appreciate the feedback. Thanks.

**Comment by rnyak** [comment]
@rjzamora Hello. I created the FEA above. it is challenging to do that op since it requires calculation of `nunique()`? thanks.

**Comment by rjzamora** [comment]
I guess the "challenge" here is that the `fit` method for this op would be doing something very similar to `Categorify.fit` (perhaps the exact same thing), and I don't think there is any obvious way to avoid duplicating the work in NVTabular (yet). Therefore, if you are dropping columns based on unique AND using Categorify, you will be sampling unique values twice.  If you will **always** be calling `Categorify` on the columns that are not being dropped by your op, then I suppose you could just add a new option in `Categoify` to drop columns with too few uniques.
