### ISSUE TITLE
[BUG] Criteo dataset transformed by NVTabular 0.10.0 does not work with HugeCTR

### ISSUE THREAD

**Issue by leiterenato** [NVIDIA-Merlin/NVTabular#1408]
**Describe the bug**
Using NVTabular to transform the Criteo dataset causes HugeCRT training to not work.

When I start the training process, I receive this error:
```
Runtime error: Parquet reader: Dense KeyType and Parquet column type don't match /hugectr/HugeCTR/include/data_readers/parquet_data_reader_worker.hpp:361 

Runtime error: Parquet reader: Dense KeyType and Parquet column type don't match /hugectr/HugeCTR/include/data_readers/parquet_data_reader_worker.hpp:361
```

The data (CSV files) used to run the NVTabular transformation pipeline is located in a Google Cloud Storage bucket.
The CSV files were downloaded locally and uploaded to GCS. From there I convert the CSVs to Parquet, define a workflow, transform the data and write back to GCS.

**Steps/Code to reproduce bug**
1) Upload 1 file (1 day of Criteo dataset) to a GCS bucket
2) Create an instance with GPU on GCP
3) Run the following scripts to transform the data and train a model

Preprocessing code:
https://gist.github.com/leiterenato/868bfcc50cfbcd3252267c6082be057e

HugeCTR Model code:
https://gist.github.com/leiterenato/51800400042db86232645f7a23f7624a

**Expected behavior**
Finish training the model.

**Environment details (please complete the following information):**
 - Instance on Google Cloud with GPU (1 x A100) + Criteo files located in a GCS bucket
 - NVTabular on merlin-training ngc container (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-training)
    .**Version 22.02**

**Additional context**
IMPORTANT: If I use a dataset transformed with NVTabular 0.7.0, I can train the model with HugeCTR.

Impact:
<Add impact>

**Comment by EvenOldridge** [comment]
@bschifferer can you take a look at this and see if you can repro.

**Comment by bschifferer** [comment]
I tested the latest NVTabular Version (current main) + HugeCTR 3.4 and it works for me locally (not using Google Cloud or GCS).

@leiterenato have you tested copying the data from GCS to local disk and train with HugeCTR?

**Comment by viswa-nvidia** [comment]
@leiterenato , bump

**Comment by leiterenato** [comment]
Thanks for testing this alternative.
Yes, it works with local filesystem.
But I need to work with Google Cloud Storage.

Em sex., 1 de abr. de 2022 11:33, bschifferer ***@***.***>
escreveu:

**Comment by EvenOldridge** [comment]
@leiterenato the location of the dataset is very important in terms of achieving good performance.  The I/O between network storage and the GPU is much slower than if you copy to a local NVME.  In our testing the copy+training on local NVME is 2-5x faster than training directly on cloud storage.
