### ISSUE TITLE
[BUG] tests/unit/test_tf4rec.py is failing on main

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/NVTabular#1418]
**Describe the bug**
`tests/unit/test_tf4rec.py` is failing on `main`.  This is probably due to the changes in `core`.

**Steps/Code to reproduce bug**
Run `pytest tests/unit/test_tf4rec.py`

**Expected behavior**
Test doesn't fail.

**Environment details (please complete the following information):**
Running this on Ubuntu server. Installing everything using `pip install -e .`
 

**Additional context**
I want to learn more about the codebase and learn to use NVTabular. `tests/unit/test_tf4rec.py` seems like a really interesting test leveraging much of the functionality. Happy to troubleshoot this and open a PR with a fix. If it would be a good time to start working on this please assign this to me. Thank you!

**Comment by radekosmulski** [comment]
Seems in `tests/unit/test_tf4rec.py`  `ItemRecency` is outputting two columns where if I am reading it right the original intent was for it to output a single column.

And then when this gets fed into the ops that comprise `recency_features_norm` the problem arises.

Also, I believe `output_column_names` on `ItemRecency` is never called.

```
from nvtabular.ops import Operator

# custom op for item recency
class ItemRecency(Operator):
    def transform(self, columns, gdf):
        for column in columns.names:
            col = gdf[column]
            item_first_timestamp = gdf["prod_first_event_time_ts"]
            delta_days = (col - item_first_timestamp) / (60 * 60 * 24)
            gdf[column + "_age_days"] = delta_days * (delta_days >= 0)
        return gdf

    def output_column_names(self, columns):
        return ColumnSelector([column + "_age_days" for column in columns.names])

    def dependencies(self):
        return ["prod_first_event_time_ts"]

recency_features = ["event_time_ts"] >> ItemRecency()
recency_features_norm = (
    recency_features
    >> nvt.ops.LogOp()
    >> nvt.ops.Normalize()
    >> nvt.ops.Rename(name="product_recency_days_log_norm")
)

dataset = nvt.Dataset(df)

workflow = nvt.Workflow(recency_features)
workflow.fit(dataset)
sessions_gdf = workflow.transform(dataset).to_ddf().compute()
sessions_gdf.head()
```

![image](https://user-images.githubusercontent.com/2444926/156247833-0a9322d7-8e91-47fc-8737-008e3ac300b9.png)

This is as far as I got, need to run now.

**Comment by karlhigley** [comment]
We're having a few issues getting cross-repo dependencies and testing ironed out as the Merlin ecosystem expands, but this issue should be resolved by NVIDIA-Merlin/core#29.

**Comment by karlhigley** [comment]
`output_column_names` not getting called is expected; earlier versions of NVTabular used that method to determine their outputs, but we have since shifted to relying on `column_mapping`, which produces a dictionary of `output_column -> [input_columns]` pairs (which helps us compute the correct schema info like dtype for the output columns based on the inputs they're generated from.) I don't think the example this test is based on has been updated to reflect that yet.

**Comment by radekosmulski** [comment]
Thank you very much for this additional information, @karlhigley! All this makes it much easier to understand what is going on!

I updated `ItemRecency`, the results are now correctly returned.
