### ISSUE TITLE
[FEA] Set the same IntDomain name for joint encoded categorical columns

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/NVTabular#1484]
**Describe the solution you'd like**

In Merlin Models, we base the logic of generating shared embeddings between two or multiple categorical features on the name of the `IntDomain` property in the Schema object. (The code reference [here](https://github.com/NVIDIA-Merlin/models/blob/303a91eebb4859c7d4c5065f345b33e45962c69e/merlin/models/tf/features/embedding.py#L139#L150)). 

Based on the discussion initiated by @karlhigley,  NVT workflow should support the logic of setting the same `IntDomain` name for columns with shared vocabularies.  

**Additional context**
A possible solution could be to include the logic of setting the IntDomain name in the `Categorify` operation: when a group of columns is jointly encoded, we could create one IntDomain object with the same name for each of the specified columns in the schema.

**Comment by karlhigley** [comment]
(Uncovered missing functionality as a result of #1461)
