### ISSUE TITLE
[DOC]NVTabular - Readme bash v1.0

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/NVTabular#1490]
- [ ] Update the environment files for cuda 11.4 and 11.5?

“Use the environment files that have been provided to install the CUDA Toolkit (11.0 or 11.2).”

- [ ] Create Merlin-core github issue templates

- [ ] Support matrix should be moved out of NVTabular documentation ,and included in NVIDIA-Merlin/Merlin docs.  
- NVT README needs updated after moving to reflect the change https://github.com/NVIDIA-Merlin/NVTabular/blob/main/docs/source/resources/support_matrix.rst

- [ ] Move table of docker containers to one central location - rather than in NVT+merlin-core

- [x] Maybe we can add a sentence to mention that “NVTabular installed with pip runs only on CPU”.

**Comment by karlhigley** [comment]
Updated the README, the Docker container and support matrix issues are already tracked elsewhere, and I've created issues for the remaining two tasks, neither of which is a blocker.

**Comment by viswa-nvidia** [comment]
@karlhigley , thanks
