### ISSUE TITLE
[BUG] getting error when sending request to TIS after loading a TF4Rec PyT model

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1502]
This happens when serving end-to-end-notebook example to Triton.  This is related to `export_pytorch_ensemble` is not generating the configs properly.

Please refer to this issue on TF4Rec repo to repro:  https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/400

**Comment by viswa-nvidia** [comment]
@EvenOldridge , Please assign an engineer for this bug

**Comment by viswa-nvidia** [comment]
Reduced priority to P1
