### ISSUE TITLE
[BUG] PyTorch Loader Test Errors

### ISSUE THREAD

**Issue by albert17** [NVIDIA-Merlin/NVTabular#1506]
These tests fail when running alll NVTabular Unit tests together in Merlin-Pytorch-Training container in a Multi-GPU environment

If they are run individually they work fine

```
FAILED tests/unit/loader/test_torch_dataloader.py::test_horovod_multigpu
FAILED tests/unit/loader/test_torch_dataloader.py::test_distributed_multigpu
```

**Comment by EvenOldridge** [comment]
Horovod isn't officially supported by DLFW Pytorch.  They recommend a different distributed method.  We're planning to remove the examples for now: https://github.com/NVIDIA-Merlin/NVTabular/pull/1530
