### ISSUE TITLE
[BUG] Movielens multi-gpu training with PyT model example gives error when training

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1514]
**Describe the bug**

01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb training step is not working as expected.

**Steps/Code to reproduce bug**
Please run the this notebook to repro the issue

01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 
`merlin-pytorch-training:22.04` container was used.

**Comment by karlhigley** [comment]
What's the error?

**Comment by benfred** [comment]
We removed the example in https://github.com/NVIDIA-Merlin/NVTabular/pull/1530 - this is no longer an issue
