### ISSUE TITLE
Download Criteo dataset does not work (link not working)

### ISSUE THREAD

**Issue by anilrapt** [NVIDIA-Merlin/NVTabular#1543]
https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/01-Download-Convert.ipynb

download_file(
                "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_"
                + str(i)
                + ".gz",
                file,
            )

does not download.  
Checking if the above link is still a working one. If not, can you please let us know if there are any alternative links to download the dataset.
Thanks.

The following is the error, we get ...
==============================================
downloading day_0.gz: 0.00B [00:00, ?B/s]

---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
File /usr/lib/python3.8/urllib/request.py:1354, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1353 try:
-> 1354     h.request(req.get_method(), req.selector, req.data, headers,
   1355               encode_chunked=req.has_header('Transfer-encoding'))
   1356 except OSError as err: # timeout error

File /usr/lib/python3.8/http/client.py:1256, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1255 """Send a complete request to the server."""
-> 1256 self._send_request(method, url, body, headers, encode_chunked)

File /usr/lib/python3.8/http/client.py:1302, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1301     body = _encode(body, 'body')
-> 1302 self.endheaders(body, encode_chunked=encode_chunked)

File /usr/lib/python3.8/http/client.py:1251, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1250     raise CannotSendHeader()
-> 1251 self._send_output(message_body, encode_chunked=encode_chunked)

File /usr/lib/python3.8/http/client.py:1011, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1010 del self._buffer[:]
-> 1011 self.send(msg)
   1013 if message_body is not None:
   1014 
   1015     # create a consistent interface to message_body

File /usr/lib/python3.8/http/client.py:951, in HTTPConnection.send(self, data)
    950 if self.auto_open:
--> 951     self.connect()
    952 else:

File /usr/lib/python3.8/http/client.py:922, in HTTPConnection.connect(self)
    921 """Connect to the host and port specified in __init__."""
--> 922 self.sock = self._create_connection(
    923     (self.host,self.port), self.timeout, self.source_address)
    924 self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

File /usr/lib/python3.8/socket.py:787, in create_connection(address, timeout, source_address)
    786 err = None
--> 787 for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    788     af, socktype, proto, canonname, sa = res

File /usr/lib/python3.8/socket.py:918, in getaddrinfo(host, port, family, type, proto, flags)
    917 addrlist = []
--> 918 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    919     af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
File <timed exec>:30, in <module>

File /core/merlin/core/utils.py:115, in download_file(url, local_filename, unzip_files, redownload)
    112         opener.addheaders = [("Accept-Encoding", "gzip, deflate"), ("Accept", "*/*")]
    114         urllib.request.install_opener(opener)
--> 115         urllib.request.urlretrieve(url, local_filename, reporthook=report)  # nosec
    117 if unzip_files and local_filename.endswith(".zip"):
    118     with zipfile.ZipFile(local_filename) as z:

File /usr/lib/python3.8/urllib/request.py:247, in urlretrieve(url, filename, reporthook, data)
    230 """
    231 Retrieve a URL into a temporary location on disk.
    232 
   (...)
    243 data file as well as the resulting HTTPMessage object.
    244 """
    245 url_type, path = _splittype(url)
--> 247 with contextlib.closing(urlopen(url, data)) as fp:
    248     headers = fp.info()
    250     # Just return the local path and the "headers" for file://
    251     # URLs. No sense in performing a copy unless requested.

File /usr/lib/python3.8/urllib/request.py:222, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220 else:
    221     opener = _opener
--> 222 return opener.open(url, data, timeout)

File /usr/lib/python3.8/urllib/request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    522     req = meth(req)
    524 sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525 response = self._open(req, data)
    527 # post-process response
    528 meth_name = protocol+"_response"

File /usr/lib/python3.8/urllib/request.py:542, in OpenerDirector._open(self, req, data)
    539     return result
    541 protocol = req.type
--> 542 result = self._call_chain(self.handle_open, protocol, protocol +
    543                           '_open', req)
    544 if result:
    545     return result

File /usr/lib/python3.8/urllib/request.py:502, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    500 for handler in handlers:
    501     func = getattr(handler, meth_name)
--> 502     result = func(*args)
    503     if result is not None:
    504         return result

File /usr/lib/python3.8/urllib/request.py:1383, in HTTPHandler.http_open(self, req)
   1382 def http_open(self, req):
-> 1383     return self.do_open(http.client.HTTPConnection, req)

File /usr/lib/python3.8/urllib/request.py:1357, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1354         h.request(req.get_method(), req.selector, req.data, headers,
   1355                   encode_chunked=req.has_header('Transfer-encoding'))
   1356     except OSError as err: # timeout error
-> 1357         raise URLError(err)
   1358     r = h.getresponse()
   1359 except:

URLError: <urlopen error [Errno -2] Name or service not known>
=================================================

**Comment by karlhigley** [comment]
See also: https://github.com/NVIDIA-Merlin/HugeCTR/issues/310

**Comment by viswa-nvidia** [comment]
We've reached out to the Criteo team about this.
