### ISSUE TITLE
[BUG] RAPIDs 22.04 and NVTabular 1.0 can't seem to coexist in the same conda env

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA-Merlin/NVTabular#1562]
**Describe the bug**

RAPIDs 22.04 and NVTabular 1.0 can't seem to coexist in the same `conda` env? 

**Steps/Code to reproduce bug**

run the conda install command for rapids then run the conda install command for nvtabular into the same env

```

conda create -n rapids-22.04 -c rapidsai -c nvidia -c conda-forge \
    rapids=22.04 python=3.8 cudatoolkit=11.5 dask-sql

conda install -n rapids-22.04 -c nvidia -c rapidsai -c numba -c conda-forge nvtabular

```

**Expected behavior**

It should install correctly

**Environment details (please complete the following information):**
 
Installing in docker env based on nvidia/cuda:11.5.1-cudnn8-runtime-ubuntu20.04

- Environment location: [Docker]
 - Method of NVTabular install: [conda]

**Comment by benfred** [comment]
Thanks for the report @Data-drone  - this should be fixed now. The issue was that the version of nvtabular / merlin-core up on conda was being too strict about the dask version that was required.  You should be able to install - using NVT v1.1.1 onwards.
