### ISSUE TITLE
[QST] Are tensorflow layer based transformations supported through LambdaOp?

### ISSUE THREAD

**Issue by silpara** [NVIDIA-Merlin/NVTabular#1570]
Following an approach similar to using tf.feature_column.categorical_column_with_hash_bucket and tf.feature_column.embedding_column in [accelerating-tensorflow.ipynb](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=6bbe5bf100df8738fe827f01e2aa581eadc90ade&device=unknown&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4e56494449412d4d65726c696e2f4e56546162756c61722f366262653562663130306466383733386665383237663031653261613538316561646339306164652f6578616d706c65732f74656e736f72666c6f772f616363656c65726174696e672d74656e736f72666c6f772e6970796e62&logged_in=false&nwo=NVIDIA-Merlin%2FNVTabular&path=examples%2Ftensorflow%2Faccelerating-tensorflow.ipynb&platform=android&repository_id=252778465&repository_type=Repository&version=99), I tried the following to create an online workflow but it failed.

```
user_lookup = tf.keras.layers.IntegerLookup(vocabulary=user_list, num_oov_indices=1)
user_embedding = tf.keras.layers.Embedding(len(user_list) + 1, 32)

item_lookup = tf.keras.layers.IntegerLookup(vocabulary=item_list, num_oov_indices=1)
item_embedding = tf.keras.layers.Embedding(len(item_ist) + 1, 32)

user_vector = ["user_id"] >> nvt.ops.LambdaOp(user_lookup) >> nvt.ops.LambdaOp(user_embedding)
item_vector = ["catalog_id"] >> nvt.ops.LambdaOp(item_lookup) >> nvt.ops.LambdaOp(item_embedding)

features = user_vector + item_vector
workflow = nvt.Workflow(features)

train = nvt.Dataset(TRAIN_PATHS, engine="parquet")
workflow.fit(train)
train_ds = KerasSequenceLoader(
    workflow.transform(train),
    cat_names=CATEGORICAL_COLUMNS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    buffer_size=0.06,
    parts_per_chunk=8,
    engine='parquet'
)

```
This results in the error
```

Failed to transform operator <nvtabular.ops.lambdaop.LambdaOp object at 0x7fd096546340>
Traceback (most recent call last):
  File "/home/ec2-user/anaconda/envs/dl/lib/python3.8/site-packages/nvtabular/workflow/workflow.py", line 462, in _transform_partition
    output_df = node.op.transform(selection, input_df)
  File "/home/ec2-user/anaconda/envs/dl/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/ec2-user/anaconda/envs/dl/lib/python3.8/site-packages/nvtabular/ops/lambdaop.py", line 72, in transform
    new_df[col] = self.f(df[col], df)
  File "/home/ec2-user/anaconda/envs/dl/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ec2-user/anaconda/envs/dl/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
    return fn(*args, **kwargs)
TypeError: call() takes 2 positional arguments but 3 were given
```

Are these tf layers based operations supported in workflow? If not, is there an alternate way to do the same?

**Comment by EvenOldridge** [comment]
NVT workflows support dask_cudf or cudf operations in lambda ops, but not TF operations.  You'd either need to build the equivalent functionality in dask_cudf or perform the calls first in TF and then convert using dlpack.  Can you describe the problem you're trying to solve with this code?
