### ISSUE TITLE
[FEA] Refitting an already fitted workflow for faster iteration

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/NVTabular#1571]
**Is your feature request related to a problem? Please describe.**
When we are first getting started with NVTabular and doing a bunch of iterations, sometimes, we would only make a very small change to the workflow; however, even with a very small change, we would still need to re-fit the workflow on the dataset. 

For example, if we added a `ValueCount()` operator to of the columns, though the output of the preprocessing would virtually be the same and most columns would not be affected, we would still need to re-fit the entire dataset.

**Describe the solution you'd like**
So, I wish NVTabular had some way to load back the already fitted workflow to re-fit portions of it slightly differently.

**Describe alternatives you've considered**
We could simply always work with smaller datasets as we get started so the actual fitting is very quick.

CC: @rnyak

**Comment by EvenOldridge** [comment]
Iterative fitting is something we've considered and would like to do but it's a little ways down our roadmap.  We're going to try to line it up with iterative retraining as well.

**Comment by shoyasaxa** [comment]
Got it - thank you for letting me know!
