### ISSUE TITLE
[BUG] Groupby aggregations on non float64 columns throws an error

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/NVTabular#1574]
**Describe the bug**
When running `Groupby` on columns with a dtype other than `float64`, I receive the following error:

```
TypeError: Dtype discrepancy detected for column measurement_std: operator Groupby reported dtype `float32` but returned dtype `float64`.
```

**Steps/Code to reproduce bug**
![image](https://user-images.githubusercontent.com/2444926/172293775-eed58ba1-d4c4-4b5e-a06e-1a08be97636b.png)

Here is code that can be copied over
```
import cudf
import nvtabular as nvt

gdf = cudf.DataFrame(data={'cat': ['a', 'a', 'b'], 'timestamp': [1, 2, 1], 'measurement': [0.1, 0.2, 0.5]})

gdf.measurement = gdf.measurement.astype('float32')

out = ['measurement', 'cat'] >> nvt.ops.Groupby('cat', aggs=['std'])


ds = nvt.Dataset(gdf)
wf = nvt.Workflow(out)
res = wf.fit_transform(ds)

res.compute()
```

**Expected behavior**
The transformation to work, results to be returned without error.

**Environment details (please complete the following information):**
`merlin-pytorch-training:22.05` image with all Merlin repos updated and pip installed today

**Comment by rnyak** [comment]
@radekosmulski thanks for reporting the issue. As an alternative may be you can use `JoinGroupby`:

```
import cudf
import nvtabular as nvt

gdf = cudf.DataFrame(data={'cat': ['a', 'a', 'b'], 'timestamp': [1, 2, 1], 'measurement': [0.1, 0.2, 0.5]})

gdf.measurement = gdf.measurement.astype('float32')

out = ['cat'] >> nvt.ops.JoinGroupby(stats=['std'], cont_cols=['measurement']) >> nvt.ops.Rename(name = 'measurement_std')

ds = nvt.Dataset(gdf)
wf = nvt.Workflow(out)
res = wf.fit_transform(ds)

res.compute()
```
