### ISSUE TITLE
[BUG] pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found

### ISSUE THREAD

**Issue by BenikaHall** [NVIDIA-Merlin/NVTabular#1613]
**Describe the bug**
When starting the dask cluster, we are unable to start the CUDA context. We get the error pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found

**Steps/Code to reproduce bug**
```
from dask.distributed import Client, wait 
from dask_cuda 
import LocalCUDACluster 
import dask as dask, dask_cudf

CUDA_SPILL_LIMIT_PERC = 0.8

spill_limit = device_mem_size(kind="total") * CUDA_SPILL_LIMIT_PERC # Spill device mem to host at this limit

cluster = LocalCUDACluster(local_directory = dask_workdir,
                           device_memory_limit = spill_limit)
client = Client(cluster)

client
```

**Expected behavior**
Expected to see the dask_cuda.LocalCUDACluster initialized and the client started.

Client
Connection method: Cluster object | Cluster type: dask_cuda.LocalCUDACluster

Dashboard:  http://127.0.0.1:8787/status 

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of NVTabular install: Docker
 - merlin-tensorflow-inference:22.05 container
 - Python version - 3.9.13
 - cudf version - 22.06.01
 - dask_cudf version - 22.06.01
 - CUDA version - 11.6
 - Driver version - 418.126.02 **(cannot change)**

**Additional context**
At this time, I can't update the driver version. 
Is there a workaround to this issue? It is similar to this bug - https://github.com/NVIDIA-Merlin/NVTabular/issues/1601

**Comment by rnyak** [comment]
@rjzamora fyi.

**Comment by sohn21c** [comment]
@pentschev @rjzamora 
This bug is very similar to https://github.com/NVIDIA-Merlin/NVTabular/issues/1601, but unfortunately, updating the Driver version is difficult. Do you have any proposal to resolve the issue?

**Comment by pentschev** [comment]
I answered this question in https://github.com/rapidsai/dask-cuda/issues/951#issuecomment-1184156743, unfortunately I can't suggest any other alternatives as this is a CUDA limitation.
