### ISSUE TITLE
[BUG] Warning of number of parquet files is wrong

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/NVTabular#1621]
**Describe the bug**
I convert a dataset of .csv files to .parquet with
```
dataset.to_parquet(output_path, out_files_per_proc=40)
```
and I get the warning
```
/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py:862: UserWarning: Only created 1 files did not have enough partitions to create 40 files.
  warnings.warn(
```

However, I can see 40 files in the output directory

**Comment by rjzamora** [comment]
I think this was closed by https://github.com/NVIDIA-Merlin/core/pull/159. However, please re-open if the warning is still incorrect.
