### ISSUE TITLE
[FEA] Obtain a workflow for predicting from workflow for training

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/NVTabular#1630]
**Is your feature request related to a problem? Please describe.**
To train, you create a `Workflow` that you fit on your `train` data and use to transform `train` and `valid` data.

```
out = [...] << nvt.ops....
workflow = nvt.Workflow(out)

train_ds = workflow.fit_transform(train)
valid_ds = workflow.transform(valid)
```

But what do you do if you want to predict on unseen data or use `merlin-systems` to deploy a model?

The original workflow might be transforming the targets. But even if no transformation is applied to targets, targets still need to be included in the input data and are outputted when `transform` is called. This functionality is needed so that we can train our model. But using this workflow to transform unseen data will not work as such data will not contain targets and the workflow will terminate with an error.

We should be able to use a single workflow for transforming inputs for training and for transforming inputs for inference. We could create a separate workflow for inference, but that defeats the purpose of having a workflow -- a big reason for having a workflow is to ensure the same transformations are applied throughout the lifecycle of our model. Having to create two pipelines would open up the possibility of introducing one of the subtlest of bugs affecting model performance that can go undetected for years (that is, where inputs in training and production are processed in a slightly different way)

**Describe the solution you'd like**
Something along the lines of:

`test_ds = workflow.transform(test, omit_targets=True)`

to omit any transformations applied to target columns.

**Describe alternatives you've considered**
One workaround is to create dummy columns for your targets when performing inference on unseen data or doing inference in production. Another workaround would be to create and fit two separate pipelines.

But I don't think either is an acceptable solution from a usability/ML best practices perspective.

**Comment by benfred** [comment]
We have `remove_inputs` method on the workflow that I think will do what you're asking for:

https://github.com/NVIDIA-Merlin/NVTabular/blob/465fb4e0cddc1385aff5a89595e62c159d794e8c/nvtabular/workflow/workflow.py#L147-L168

So something like

```
inference_workflow = workflow.remove_inputs(["target_column_name"])
test_ds = inference_workflow.transform(test)
```

**Comment by radekosmulski** [comment]
closing, opened #1632
