### ISSUE TITLE
[BUG] `Workflow#remove_inputs` doesn't work

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/NVTabular#1632]
**Describe the bug**

`Workflow#remove_inputs` doesn't work.

![image](https://user-images.githubusercontent.com/2444926/180338997-37b18407-a11c-48bd-9838-a167fd5689c4.png)
![image](https://user-images.githubusercontent.com/2444926/180339005-0439d5b6-c2a1-4042-9647-67c20b7321c2.png)

**Steps/Code to reproduce bug**
Code to repro:
```
import cudf
import nvtabular as nvt
import numpy as np

gdf = cudf.DataFrame(data={'cat': list('abcde'), 'target': np.random.randn(5)})
gdf

train_ds = nvt.Dataset(gdf.iloc[:3])
test_ds = nvt.Dataset(gdf.iloc[3:].drop(columns='target'))

output = ['cat'] >> nvt.ops.Categorify()
output += ['target']

workflow = nvt.Workflow(output)
workflow.fit_transform(train_ds).compute()

workflow.remove_inputs(['target']).transform(test_ds).compute()
```

**Expected behavior**
Input columns along with any ops on them are removed from the graph.

**Environment details (please complete the following information):**
 Container `nvcr.io/nvidia/merlin/merlin-pytorch:22.06`

**Additional context**
This is very useful to have for serving.

**Comment by radekosmulski** [comment]
I just got a chance to test this out and I think this wasn't fixed
![image](https://user-images.githubusercontent.com/2444926/181139376-b8edde75-3900-467a-8cb6-d8b22dca3485.png)

reproducer code:
```
import cudf
import nvtabular as nvt
import numpy as np
import datetime

purchases = cudf.DataFrame(
    data={
        'customer_id': np.random.randint(0, 10, 1000),
        'price': np.random.rand(1000),
        'target': np.random.randint(1, 50, 1000)
})

ds = nvt.Dataset(purchases)

price = ['price'] >> nvt.ops.Normalize()

wf = nvt.Workflow(price + ['target'])

wf.fit_transform(ds).compute()
wf.remove_inputs('target')
wf.transform(ds).compute()
```

Would you be so kind please and take another look at this? Thank you!!!

**Comment by bschifferer** [comment]
Can you try `wf.remove_inputs(['target'])` intsead of `wf.remove_inputs('target')` ?

**Comment by radekosmulski** [comment]
This works like a charm, my bad! Thank you very much for your help, @bschifferer 🙂 It even is able to remove columns that had ops run on them! Awesome!
