### ISSUE TITLE
Can I install NVTabular from source? [QST]

### ISSUE THREAD

**Issue by zxgx** [NVIDIA-Merlin/NVTabular#1640]
**What is your question?**
I've installed NVTabular for 3 times today, and each time I encountered a different bug. It's quite torturing.

The latest error was the closest to success, however it reported the following error.
![image](https://user-images.githubusercontent.com/34452939/183624668-f3e71665-f7f3-41f5-a066-0158d045d650.png)

It seems like a version issue of dependency cudf, and I also met other different dependencies issues in the previous failed installations.
However, I cannot control the dependencies verion since I installed NVTabular from conda.
So, can I install NVTabular from source?

**Comment by zxgx** [comment]
I've tried the official merlin-pytorch image, and met another bug.
Please see: [https://github.com/rapidsai/dask-cuda/issues/974](https://github.com/rapidsai/dask-cuda/issues/974)

**Comment by rnyak** [comment]
@zxgx sorry for the inconvenience. Are you trying to run  this notebook: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/01-Download-Convert.ipynb ?

**Comment by rnyak** [comment]
@zxgx  can you please give more information regarding your env? where do you want to install NVTabular? in a conda env?  are you running notebooks in a cloud instance? what's your HW? can you pls share your driver version, nvidia-smi output, and `nvcc --version` output. thanks.

**Comment by rnyak** [comment]
@zxgx do you still have a question?
