### ISSUE TITLE
[DOC] How to launch NVTabular/examples/multi-gpu-movielens/torch_trainer_dist.py?

### ISSUE THREAD

**Issue by zxgx** [NVIDIA-Merlin/NVTabular#1650]
## Report needed documentation

**Report needed documentation**
I want to know how to launch the script: [torch_trainer_dist](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/torch_trainer_dist.py), because I want to integrate NVTabular dataloader in my code, in which I launch the distributed setting with torchx/torchrun.

**Describe the documentation you'd like**
A jupyter notebook similar to https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb would be great.

**Comment by zxgx** [comment]
Hi, I've made some progress on this issue, but also met some new problems.
I summarized in this discussion: https://github.com/dask/dask/discussions/9405.
Could you please help me to figure it out?

**Comment by karlhigley** [comment]
Unfortunately, we no longer support the combination of PyTorch and Horovod. This file should have been removed from the repo, but must have been missed when we dropped PyTorch/Horovod support.
