### ISSUE TITLE
[BUG] Columns are tagged as `categorical` after applying TargetEncoding op 

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1670]
**Describe the bug**
When we apply TargetEncoding, the features in the schema file are tagged as `categorical`, however they should be  tagged as `continuous` instead.

**Steps/Code to reproduce bug**
Please run the code below to repro the issue:

```
import nvtabular as nvt
from nvtabular.ops import TargetEncoding,  LambdaOp
from merlin.core import dispatch 

df = dispatch.make_df({
    'label1': list(range(10)),
    'cat1': list(range(10)),
    'cat2': list(range(10)),
})

label = ['label1'] >> LambdaOp(lambda col: (col>0).astype('int8'))
target_encode = ['cat1', 'cat2'] >> TargetEncoding(label, kfold=5, out_dtype="float32")

workflow = nvt.Workflow(target_encode)

dataset = nvt.Dataset(df)

workflow.fit(dataset)
workflow.transform(dataset).to_parquet(output_path=  "./train/")
```
Once you run the code above, open the `train` folder and checkout the `schema.pbtxt`.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
  
I am using `merlin-tensorflow:22.07` image with the latest main branches pulled.

**Comment by karlhigley** [comment]
@rnyak I think your proposed fix of switching it over to `Tags.CONTINUOUS` makes sense
