### ISSUE TITLE
[BUG] GroupBy does not aggregate correctly vector features

### ISSUE THREAD

**Issue by fdtomasi** [NVIDIA-Merlin/NVTabular#1678]
**Describe the bug**
Vector features are wrongly aggregated by GroupBy operator.

**Steps/Code to reproduce bug**
```python
import pandas as pd
import nvtabular as nvt
from nvtabular import ops as nvt_ops

df = pd.DataFrame(dict(
    user_id=[1, 1, 2, 3], user_vector=[[1,2,3], [1,2,3], [2,2,3], [3,2,3]],
    item_id=["a", "b", "a", "b"], item_vector=[[10,20,30], [20,40,60], [10,20,30], [20,40,60]],
))

df
output = df.columns >> nvt_ops.Groupby(groupby_cols="user_id", aggs=dict(user_vector="first", item_id="list", item_vector=list))
workflow = nvt.Workflow(output)
ds = nvt.Dataset(df)
out = workflow.fit_transform(ds).compute()

out
```
Now, the behaviour is:
`out["user_vector_first"] == [1, 3, 1]`
which does not make sense.

**Expected behavior**
`out["user_vector_first"] == [[1,2,3], [2,2,3], [3,2,3]]`

The correct output is given by pandas:
```
df.groupby("user_id").agg(
    user_vector=("user_vector", lambda x: x.iloc[0]),
    item_id=("item_id", list),
    item_vector=("item_vector", list),
).reset_index()
```

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider) Bare-metal 
 - Method of NVTabular install: [conda, Docker, or from source]  conda
 - `nvtabular==1.4.0, rapids==22.08, cudf==22.06`

Additional Context:
This was not an issue with an environment create with rapids==22.04.

**Comment by rnyak** [comment]
@rjzamora do we have support for this in groupby? this is trying to group the list entires..

**Comment by rjzamora** [comment]
Thanks for raising this @fdtomasi!  It looks like NVTabular should be updated to use `cudf`'s `list.get` to properly handle then list-of-lists case.  The current implementation assumes you are never using a list-based aggregation on a list column, so it always flattens the list.

For example, I believe [these lines](https://github.com/NVIDIA-Merlin/NVTabular/blob/8f87c3471604d44937ea97363841b8faee70872c/nvtabular/ops/groupby.py#L300-L302) can become `return x.list.get(0)`, and [these lines](https://github.com/NVIDIA-Merlin/NVTabular/blob/8f87c3471604d44937ea97363841b8faee70872c/nvtabular/ops/groupby.py#L313-L315) can become `return x.list.get(-1)`.

I'll be happy to make these changes soonish, but Ill mark this as a "good first issue" in case someone else wants to give it a try.
