### ISSUE TITLE
ModuleNotFoundError: No module named 'merlin.dag.executors'

### ISSUE THREAD

**Issue by gauravgund** [NVIDIA-Merlin/NVTabular#1684]
Hi,
I am trying to import nvtabular but I m getting the following error:

! pip install -U merlin-models
!pip install -U merlin-core
! pip install -U pynvml
! pip install -U nvtabular

import nvtabular as nvt 

error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-31-5df2acaa633f>](https://localhost:8080/#) in <module>
----> 1 import nvtabular

2 frames
[/usr/local/lib/python3.7/dist-packages/nvtabular/__init__.py](https://localhost:8080/#) in <module>
     22 from merlin.dag import ColumnSelector
     23 from merlin.schema import ColumnSchema, Schema
---> 24 from nvtabular import workflow  # noqa
     25 from nvtabular import _version
     26 

[/usr/local/lib/python3.7/dist-packages/nvtabular/workflow/__init__.py](https://localhost:8080/#) in <module>
     17 # flake8: noqa
     18 from nvtabular.workflow.node import WorkflowNode
---> 19 from nvtabular.workflow.workflow import Workflow

[/usr/local/lib/python3.7/dist-packages/nvtabular/workflow/workflow.py](https://localhost:8080/#) in <module>
     31 
     32 from merlin.dag import Graph
---> 33 from merlin.dag.executors import DaskExecutor
     34 from merlin.io import Dataset
     35 from merlin.schema import Schema

ModuleNotFoundError: No module named 'merlin.dag.executors'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
ModuleNotFoundError: No module named 'merlin.dag.executors'

**Comment by rnyak** [comment]
@gauravgund  you might need to update the version of 'merlin core' installed to the latest version. Can you do `cd /core && git pull origin main && pip install .` and see if the issue goes away?

Besides, is it possible for you to use merlin docker image? you can pull the latest as  below:

`docker pull nvcr.io/nvidia/merlin/merlin-tensorflow:22.09`

**Comment by gauravgund** [comment]
Hi @rnyak, I started to get this error very recently, it was working fine since last week. Moreover, I did as per your suggestions, the following is the error in the google colab:

**code:**
%%shell
cd core 
git pull origin main 
pip install .

**Error:**


ERROR: Could not find a version that satisfies the requirement distributed>=2022.3.0 (from merlin-core) (from versions: 1.0.0.linux-x86_64, 1.0.1.linux-x86_64, 1.0.2.linux-x86_64, 1.1.0.linux-x86_64, 1.2.0.linux-x86_64, 1.2.1.linux-x86_64, 1.2.2.linux-x86_64, 1.2.3.linux-x86_64, 1.3.0.linux-x86_64, 1.3.1.linux-x86_64, 1.3.2.linux-x86_64, 1.3.3.linux-x86_64, 1.4.0.linux-x86_64, 1.5.0.linux-x86_64, 1.6.0.linux-x86_64, 1.6.1.linux-x86_64, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.14.0, 1.14.1, 1.14.3, 1.15.0rc1, 1.15.0, 1.15.1, 1.15.2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.20.0, 1.20.1, 1.20.2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.21.7, 1.21.8, 1.22.0, 1.22.1, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.26.0, 1.26.1, 1.27.0, 1.27.1, 1.28.0, 1.28.1, 2.0.1, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.15.1, 2.15.2, 2.16.0, 2.17.0, 2.18.0, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2.30.1, 2020.12.0, 2021.1.0, 2021.1.1, 2021.2.0, 2021.3.0, 2021.3.1, 2021.4.0, 2021.4.1, 2021.5.0, 2021.5.1, 2021.6.0, 2021.6.1, 2021.6.2, 2021.7.0, 2021.7.1, 2021.7.2, 2021.8.0, 2021.8.1, 2021.9.0, 2021.9.1, 2021.10.0, 2021.11.0, 2021.11.1, 2021.11.2, 2021.12.0, 2022.1.0, 2022.1.1, 2022.2.0)
ERROR: No matching distribution found for distributed>=2022.3.0
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-d8e42ef1e7f7>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('shell', '', 'cd core \ngit pull origin main \npip install .\n\n')

2 frames
[/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py](https://localhost:8080/#) in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _shell_cell_magic(args, cmd)
    107   result = _run_command(cmd, clear_streamed_output=False)
    108   if not parsed_args.ignore_errors:
--> 109     result.check_returncode()
    110   return result
    111 

[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    133     if self.returncode:
    134       raise subprocess.CalledProcessError(
--> 135           returncode=self.returncode, cmd=self.args, output=self.output)
    136 
    137   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'cd core 
git pull origin main 
pip install .

' returned non-zero exit status 1.

**Comment by gauravgund** [comment]
@karlhigley @rnyak: Any updates on this please?

**Comment by karlhigley** [comment]
Based on the error you posted, it sounds like the Google Colab environment doesn't have new enough versions of `distributed` available to meet the requirements in the `main` branch of Merlin Core; not sure why though. The [latest version of `distributed`](https://pypi.org/project/distributed/#history) is `2022.9.2`, so `>=2022.3.0` isn't a particularly bleeding edge version specifier. 🤔

**Comment by gauravgund** [comment]
@karlhigley : Is there a way to solve this?

**Comment by zhiruiwang** [comment]
I encountered the same error on Python 3.7.12 with Nvtabular 1.5.0. Downgrading Nvtabular to 1.4.0 would make it work.

**Comment by gauravgund** [comment]
Thanks for the response. Is there any tutorial on @rnyak dealing with multiple implicit features (user features/item features) including text, categories and numerical features?

**Comment by rnyak** [comment]
@gauravgund we have various examples in [Merlin Models](https://github.com/NVIDIA-Merlin/models/tree/main/examples) repo. Please take a look at.

**Comment by rnyak** [comment]
@gauravgund  closing this for now, if needed please open a new ticket. thanks.
