### ISSUE TITLE
[QST] categorify multiple columns with the same feature

### ISSUE THREAD

**Issue by pyagoubi** [NVIDIA-Merlin/NVTabular#1718]
If I have multiple columns with the same feature, e.g.

| column A  | column b |
| ------------- | ------------- |
| category A  | category C  |
| category B  | category A |

how can I make sure the same mapping logic is applied to all columns, so that e.g. category A is = 1 in all columns?

**Comment by oliverholworthy** [comment]
Thanks for submitting the question @pyagoubi 

The Categorify op can be used on multiple columns as you described.

Find an example below comparing a categorify applied to two columns jointly and independently.

```python
import nvtabular as nvt
from merlin.io import Dataset
import cudf

df = cudf.DataFrame({"a": ["A", "B", "A"], "b": ["C", "A", "C"]})
dataset = Dataset(df)

# joint
# categorify multiple columns containing the same feature
workflow = nvt.Workflow([["a", "b"]] >> nvt.ops.Categorify())
workflow.fit_transform(dataset).compute()
# =>
#    a  b
#    1  2
#    3  1
#    1  2

# independent
# categorify columns independently
workflow = nvt.Workflow(["a", "b"] >> nvt.ops.Categorify())
workflow.fit_transform(dataset).compute()
# =>
#    a  b
#    1  1
#    2  2
#    1  1
```

**Comment by pyagoubi** [comment]
thanks, that is what I was looking for

**Comment by rnyak** [comment]
@ChasingStar95 

if you want to reuse a workflow on a new dataset:

- load the saved workflow
- apply transform on this dataset
```
test_dataset = Dataset(test)
workflow.transform(dataset).compute()
```

You cannot transform a column that was not used in the workflow dag. Meaning if you used columns `a` and `b` you cannot transform column `c` in another dataset. 

If you want to process `a` and `b` alone, you need to add them in the workflow pipeline as well. something like that:

```
joint_cats = [["a", "b"]] >> nvt.ops.Categorify()
single_cats = ["a", "b"] >> nvt.ops.Categorify() >> nvt.ops.Rename(postfix="_single")
outputs = joint_cats + single_cats
workflow = nvt.Workflow(outputs)
workflow.fit_transform(dataset).compute()
```

is that what you are looking for?

**Comment by ChasingStar95** [comment]
joint_cats = [["a", "b"]] >> nvt.ops.Categorify()
workflow = nvt.Workflow(outputs)
workflow.fit_transform(dataset).compute()

df = cudf.DataFrame({"a": ["A", "B", "A"], "b": ["C", "A", "C"]})

i just want to use one operation of map to all, like seq or single column with different columns names:
one category dict map of catMap to apply to all columns, like columns a, b,a_seq,b_seq,
joint_cats = [["a", "b", "a_seq","b_seq"]] >> nvt.ops.Categorify(),
but above operation cant't apply to a, b, or a, or a_seq alone.
