### ISSUE TITLE
[QST] fit transform on different features or datasets

### ISSUE THREAD

**Issue by pyagoubi** [NVIDIA-Merlin/NVTabular#1722]
I am looking for a way to apply workflow.fit() (with only one categorify step) and then transform on seperate features or a seperate dataset (like scikitlearn.preprocessing.LabelEncoder), is that possible?

**Comment by rnyak** [comment]
@pyagoubi  thanks for your question.  Yes you can use Categorify for the similar functionality happening in ` scikitlearn.preprocessing.LabelEncoder`. Here is some code snippet for you:

```
import nvtabular as nvt
from merlin.core import dispatch
from merlin.core.dispatch import make_df
from nvtabular import *

df = dispatch.make_df(
    {
        "user": ["User_A", "User_A", "User_E", "User_B", "User_C"]*2,
        "item_id": [1, 2, 1, 3, 8]*2,
        "user_categ": [101, 101, 102, 104, 105]*2,
    }
)

df_new = dispatch.make_df(
    {
        "user": ["User_A", "User_F", "User_E", "User_E", "User_C"]*2,
        "item_id": [8, 2, 4, 5, 1]*2,
        "user_categ": [101, 107, 102, 102, 105]*2,
    }
)

cat_names = ["user", "item_id", "user_categ"]

dataset = nvt.Dataset(df)
cats = cat_names >> nvt.ops.Categorify()
workflow = nvt.Workflow(cats)
# fit based on stats from df
workflow.fit(dataset)
# transform the dataset
new_gdf = workflow.transform(dataset).to_ddf().compute()
print(new_gdf)

# transform the new dataset
new_dataset = nvt.Dataset(df_new)
new_gdf2 = workflow.transform(new_dataset).to_ddf().compute()
print(new_gdf2)
```
In the example code above, we only fit the workflow once with a train set (as in SKLearn), and then we can transform the new dataset columns. Please note that, if you want to transform columns in a new (separate) dataset, the column names in the new dataset should match with the train set (the one we use to fit the workflow). 
let us know if that helps, or you have further questions.
