### ISSUE TITLE
[BUG] pip does not include latest nvtabular versions

### ISSUE THREAD

**Issue by fdtomasi** [NVIDIA-Merlin/NVTabular#1726]
**Describe the bug**
https://pypi.org/project/nvtabular/#history does not list 1.6.0 and 1.7.0 versions.

**Expected behavior**
https://pypi.org/project/nvtabular/#history should list 1.6.0 and 1.7.0 versions.

**Comment by viswa-nvidia** [comment]
We have added 1.8.1 and will be publishing consistently in the future. Thanks for posting this bug.
