### ISSUE TITLE
[QST] Possible to Cross Features on WorkFlowNode?

### ISSUE THREAD

**Issue by fabianlim** [NVIDIA-Merlin/NVTabular#1746]
It is possible to pass cross features to Operators, like so 

```python

('feat1', 'feat2') >> nvt.ops.LambdaOp(f ...)
```

However, is it possible to do the following? If I compute some workflow `node`, say
```python
node = columns >> nvt.ops.Filter(f = lambda ..)
```

and if `'feat1', 'feat2'` are columns in `node`, then can I create a cross feature and pass it to an Operator?

Ive tried the following but its not the effect I want. It will just return `node` on the subset of columns `
```python
node[[('feat1', 'feat2')]] >> nvt.ops.LambdaOp(f ...)
```

**Comment by fabianlim** [comment]
@karlhigley Right, I guess when I made up the above example I should have realized `LambdaOp` will not bother about the feature crosses, but Im glad you did understand my question.

Thanks for the tip, I will look up `HashedCross` and see how it is implemented. I guess I probably need to implement a custom operator.

**Comment by karlhigley** [comment]
If there's a missing operator re: feature crossing, let us know!
