### ISSUE TITLE
[QST] How to construct schema based on a single "items" list feature?

### ISSUE THREAD

**Issue by ardulat** [NVIDIA-Merlin/NVTabular#1820]
**What is your question?**

Hello! First, a bit of context: I am using NVTabular for further usage in Transformers4Rec. Hence, I am working on session-based recommendations. Currently, I only have one feature, an "items" list of product IDs (string). So, how do I construct a `Schema` necessary for `transformers4rec.torch.TabularSequenceFeatures`?

More context: I went through some examples of notebooks in Transformers4Rec documentation, but the main issue is related to NVTabular preprocessing. I have tried using `nvt.Workflow` to create a schema from a pandas data frame with an "items" list feature (as in the [example](https://nvidia-merlin.github.io/Transformers4Rec/main/examples/getting-started-session-based/01-ETL-with-NVTabular.html)), but I get the following:

<img width="629" alt="Screenshot 2023-05-16 at 10 00 14 PM" src="https://github.com/NVIDIA-Merlin/NVTabular/assets/20559505/6a3a842e-5663-46b7-95f7-95f6fccab7b9">

In contrast, I am trying to get something like this:

<img width="462" alt="Screenshot 2023-05-16 at 10 00 00 PM" src="https://github.com/NVIDIA-Merlin/NVTabular/assets/20559505/b77b4362-db2a-4737-8c5f-a26e99450c74">

The `item_id-list` have tags saying these are categorical features (further necessary for `TabularSequenceFeatures`). How do I get the representation of the same tags if I already have an "items" list in my data frame?

**Comment by karlhigley** [comment]
When NVT infers a schema, it can figure out the dtypes and so forth, but can't tell what the semantics of the fields are, so leaves the tags blank. You can add any additional tags with the `AddTags` operator. It accepts a list of plain strings and will auto-convert them to `Tags` if needed.

```
["item_id-list"] >> AddTags(tags=["ITEM","LIST","ITEM_ID","ID"])
```

**Comment by rnyak** [comment]
@ardulat I think this issue was resolved already?

**Comment by ardulat** [comment]
@rnyak, yes, the issue was solved at https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/703.
