### ISSUE TITLE
how to Categorify or other feature Operation to same content of different columns examples of list and simple columns[BUG]

### ISSUE THREAD

**Issue by ChasingStar95** [NVIDIA-Merlin/NVTabular#1828]
the content in column of previtems and next items  is the same feature, 
but i have no idea to Categorify them with the same operation to get the same result 
with same id.
![image](https://github.com/NVIDIA-Merlin/NVTabular/assets/14121264/d964390e-9e59-4c36-9d66-0ac10d9b2e6c)

**Comment by rnyak** [comment]
@ChasingStar95 I think we responded you in another thread. What you need  is to jointly categorify them. something like that:
```
import nvtabular as nvt
from merlin.io import Dataset
import cudf

df = cudf.DataFrame({"pre_items": [["A", "B"], ["B", "A"], ["A", "B", "C", "D"]], "next_item": ["C", "B", "E"]})

cats = [['pre_items', 'next_item']] >> nvt.ops.Categorify()

workflow = nvt.Workflow(cats)
ds = Dataset(df)
workflow.fit_transform(ds).to_ddf().compute()
```
