### ISSUE TITLE
[BUG] Saving workflows with Categorify or TargetEncoding fails to write stats files

### ISSUE THREAD

**Issue by nv-alaiacano** [NVIDIA-Merlin/NVTabular#1837]
**Describe the bug**

When using certain ops that write intermediate stats files, there is an error copying them to the destination path when saving a workflow. The error seems to be with the `_copy_storage` helper function in categorify.py which is used by:

* Categorify
* TargetEncoding
* JoinGroupby

```
E               IsADirectoryError: [Errno 21] Is a directory: '/workspace//categories/cat_stats.user_id.parquet'
```

**Steps/Code to reproduce bug**

The following test produces the error:

```python
def test_categorify_saves(tmpdir):
    N = 100

    df = Dataset(
        make_df(
            {
                "a": np.random.randint(0, 100000, N),
                "item_id": np.random.randint(0, 100, N),
                "user_id": np.random.randint(0, 100, N),
                "click": np.random.randint(0, 2, N),
            }
        ),
    )

    outputs = ["a"] >> nvt.ops.Categorify()

    continuous = (
        ["user_id", "item_id"]
        >> nvt.ops.TargetEncoding(["click"], kfold=1, p_smooth=20)
        >> nvt.ops.Normalize()
    )
    outputs += continuous
    wf = nvt.Workflow(outputs)

    wf.fit(df)
    wf.save(tmpdir)
```

**Expected behavior**

Files get copied properly to the destination.

**Comment by viswa-nvidia** [comment]
@nv-alaiacano please link the PR and close this

**Comment by nv-alaiacano** [comment]
Resolved: https://github.com/NVIDIA-Merlin/NVTabular/pull/1838
