### ISSUE TITLE
[Task] Test GPU Direct Storage with NVt

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/NVTabular#222]
Using GDS there is the potential of speeding up IO with nvtabular by up to 1.7x: https://developer.nvidia.com/blog/gpudirect-storage/ . We should test out this option with NVTabular, and add documentation about how to enable and the benefits of enabling this.

**Comment by HLuSLB** [comment]
Hi,
Is there any timeline for GDS integration?

**Comment by albert17** [comment]
Closing as we have #929
