### ISSUE TITLE
[BUG] Using TensorRT nvcr.io Hitting an error on nvtabular test run 

### ISSUE THREAD

**Issue by jperez999** [NVIDIA-Merlin/NVTabular#537]
The TensorRT nvidia/cuda:nvcr.io/nvidia/tritonserver:20.12-py3 container fails one test in the nvtabular. On a cupy error:
https://gitlab-master.nvidia.com/rapidsdl/docker/-/jobs/19481066

Couple of Facts about container
Running on 11.1
rapids install is based on cudatoolkit 11.0

**Comment by viswa-nvidia** [comment]
retiring this bug
