### ISSUE TITLE
Create a doc to track the NVTabular Software Stack 

### ISSUE THREAD

**Issue by lgardenhire** [NVIDIA-Merlin/NVTabular#914]
Viswanathan Sankaranaryanan is working on a draft. The doc will look similar to what [HugeCTR](https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/software_stack.md) currently has in place.

**Comment by viswa-nvidia** [comment]
HI Lamont, I have created a draft. Please review this with Ben, Julio, Alberto, Joey Wang and James Sohn

https://docs.google.com/spreadsheets/d/1JI7azHnmx92R0QOmRH8wqtxqBDwLwnLsdrRs8_I_YAc/edit?usp=sharing
