### ISSUE TITLE
[BUG] Criteo Test in NGC

### ISSUE THREAD

**Issue by albert17** [NVIDIA-Merlin/NVTabular#940]
[Criteo test](https://github.com/NVIDIA/NVTabular/blob/main/tests/integration/test_notebooks.py#L37) was running forever in NGC machines, but no problem in AWS machines. 

Sorry for not reporting before, since it looks like it is due to the platform I didn't think it was not in our scope.

**Comment by benfred** [comment]
@albert17 is this still an issue?

**Comment by albert17** [comment]
Closing since we not using NGC anymore
